// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CheckResultsColumns holds the columns for the "check_results" table.
	CheckResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Default: "unknown"},
		{Name: "status_code", Type: field.TypeInt, Nullable: true},
		{Name: "response_time_ms", Type: field.TypeInt, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "checked_at", Type: field.TypeTime},
		{Name: "endpoint_check_results", Type: field.TypeInt},
	}
	// CheckResultsTable holds the schema information for the "check_results" table.
	CheckResultsTable = &schema.Table{
		Name:       "check_results",
		Columns:    CheckResultsColumns,
		PrimaryKey: []*schema.Column{CheckResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "check_results_endpoints_check_results",
				Columns:    []*schema.Column{CheckResultsColumns[6]},
				RefColumns: []*schema.Column{EndpointsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// EndpointsColumns holds the columns for the "endpoints" table.
	EndpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
		{Name: "method", Type: field.TypeString, Default: "GET"},
		{Name: "interval_seconds", Type: field.TypeInt, Default: 60},
		{Name: "timeout_seconds", Type: field.TypeInt, Default: 10},
		{Name: "expected_status", Type: field.TypeInt, Default: 200},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EndpointsTable holds the schema information for the "endpoints" table.
	EndpointsTable = &schema.Table{
		Name:       "endpoints",
		Columns:    EndpointsColumns,
		PrimaryKey: []*schema.Column{EndpointsColumns[0]},
	}
	// NotificationChannelsColumns holds the columns for the "notification_channels" table.
	NotificationChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "target", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NotificationChannelsTable holds the schema information for the "notification_channels" table.
	NotificationChannelsTable = &schema.Table{
		Name:       "notification_channels",
		Columns:    NotificationChannelsColumns,
		PrimaryKey: []*schema.Column{NotificationChannelsColumns[0]},
	}
	// NotificationEventsColumns holds the columns for the "notification_events" table.
	NotificationEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "endpoint_notification_events", Type: field.TypeInt},
		{Name: "notification_channel_notification_events", Type: field.TypeInt},
	}
	// NotificationEventsTable holds the schema information for the "notification_events" table.
	NotificationEventsTable = &schema.Table{
		Name:       "notification_events",
		Columns:    NotificationEventsColumns,
		PrimaryKey: []*schema.Column{NotificationEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_events_endpoints_notification_events",
				Columns:    []*schema.Column{NotificationEventsColumns[4]},
				RefColumns: []*schema.Column{EndpointsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "notification_events_notification_channels_notification_events",
				Columns:    []*schema.Column{NotificationEventsColumns[5]},
				RefColumns: []*schema.Column{NotificationChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CheckResultsTable,
		EndpointsTable,
		NotificationChannelsTable,
		NotificationEventsTable,
	}
)

func init() {
	CheckResultsTable.ForeignKeys[0].RefTable = EndpointsTable
	NotificationEventsTable.ForeignKeys[0].RefTable = EndpointsTable
	NotificationEventsTable.ForeignKeys[1].RefTable = NotificationChannelsTable
}
