// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/monitor"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckResultCreate is the builder for creating a CheckResult entity.
type CheckResultCreate struct {
	config
	mutation *CheckResultMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *CheckResultCreate) SetStatus(v string) *CheckResultCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableStatus(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *CheckResultCreate) SetStatusCode(v int) *CheckResultCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableStatusCode(v *int) *CheckResultCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_c *CheckResultCreate) SetResponseTimeMs(v int) *CheckResultCreate {
	_c.mutation.SetResponseTimeMs(v)
	return _c
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableResponseTimeMs(v *int) *CheckResultCreate {
	if v != nil {
		_c.SetResponseTimeMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *CheckResultCreate) SetErrorMessage(v string) *CheckResultCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableErrorMessage(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetSelectionType sets the "selection_type" field.
func (_c *CheckResultCreate) SetSelectionType(v string) *CheckResultCreate {
	_c.mutation.SetSelectionType(v)
	return _c
}

// SetNillableSelectionType sets the "selection_type" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableSelectionType(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetSelectionType(*v)
	}
	return _c
}

// SetSelectionValue sets the "selection_value" field.
func (_c *CheckResultCreate) SetSelectionValue(v string) *CheckResultCreate {
	_c.mutation.SetSelectionValue(v)
	return _c
}

// SetNillableSelectionValue sets the "selection_value" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableSelectionValue(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetSelectionValue(*v)
	}
	return _c
}

// SetDiffChanged sets the "diff_changed" field.
func (_c *CheckResultCreate) SetDiffChanged(v bool) *CheckResultCreate {
	_c.mutation.SetDiffChanged(v)
	return _c
}

// SetNillableDiffChanged sets the "diff_changed" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableDiffChanged(v *bool) *CheckResultCreate {
	if v != nil {
		_c.SetDiffChanged(*v)
	}
	return _c
}

// SetDiffKind sets the "diff_kind" field.
func (_c *CheckResultCreate) SetDiffKind(v string) *CheckResultCreate {
	_c.mutation.SetDiffKind(v)
	return _c
}

// SetNillableDiffKind sets the "diff_kind" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableDiffKind(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetDiffKind(*v)
	}
	return _c
}

// SetDiffSummary sets the "diff_summary" field.
func (_c *CheckResultCreate) SetDiffSummary(v string) *CheckResultCreate {
	_c.mutation.SetDiffSummary(v)
	return _c
}

// SetNillableDiffSummary sets the "diff_summary" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableDiffSummary(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetDiffSummary(*v)
	}
	return _c
}

// SetDiffDetails sets the "diff_details" field.
func (_c *CheckResultCreate) SetDiffDetails(v string) *CheckResultCreate {
	_c.mutation.SetDiffDetails(v)
	return _c
}

// SetNillableDiffDetails sets the "diff_details" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableDiffDetails(v *string) *CheckResultCreate {
	if v != nil {
		_c.SetDiffDetails(*v)
	}
	return _c
}

// SetCheckedAt sets the "checked_at" field.
func (_c *CheckResultCreate) SetCheckedAt(v time.Time) *CheckResultCreate {
	_c.mutation.SetCheckedAt(v)
	return _c
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_c *CheckResultCreate) SetNillableCheckedAt(v *time.Time) *CheckResultCreate {
	if v != nil {
		_c.SetCheckedAt(*v)
	}
	return _c
}

// SetMonitorID sets the "monitor" edge to the Monitor entity by ID.
func (_c *CheckResultCreate) SetMonitorID(id int) *CheckResultCreate {
	_c.mutation.SetMonitorID(id)
	return _c
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (_c *CheckResultCreate) SetMonitor(v *Monitor) *CheckResultCreate {
	return _c.SetMonitorID(v.ID)
}

// Mutation returns the CheckResultMutation object of the builder.
func (_c *CheckResultCreate) Mutation() *CheckResultMutation {
	return _c.mutation
}

// Save creates the CheckResult in the database.
func (_c *CheckResultCreate) Save(ctx context.Context) (*CheckResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckResultCreate) SaveX(ctx context.Context) *CheckResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckResultCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := checkresult.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DiffChanged(); !ok {
		v := checkresult.DefaultDiffChanged
		_c.mutation.SetDiffChanged(v)
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		v := checkresult.DefaultCheckedAt()
		_c.mutation.SetCheckedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckResultCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CheckResult.status"`)}
	}
	if _, ok := _c.mutation.DiffChanged(); !ok {
		return &ValidationError{Name: "diff_changed", err: errors.New(`ent: missing required field "CheckResult.diff_changed"`)}
	}
	if _, ok := _c.mutation.CheckedAt(); !ok {
		return &ValidationError{Name: "checked_at", err: errors.New(`ent: missing required field "CheckResult.checked_at"`)}
	}
	if len(_c.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "CheckResult.monitor"`)}
	}
	return nil
}

func (_c *CheckResultCreate) sqlSave(ctx context.Context) (*CheckResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckResultCreate) createSpec() (*CheckResult, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkresult.Table, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(checkresult.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.ResponseTimeMs(); ok {
		_spec.SetField(checkresult.FieldResponseTimeMs, field.TypeInt, value)
		_node.ResponseTimeMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(checkresult.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.SelectionType(); ok {
		_spec.SetField(checkresult.FieldSelectionType, field.TypeString, value)
		_node.SelectionType = &value
	}
	if value, ok := _c.mutation.SelectionValue(); ok {
		_spec.SetField(checkresult.FieldSelectionValue, field.TypeString, value)
		_node.SelectionValue = &value
	}
	if value, ok := _c.mutation.DiffChanged(); ok {
		_spec.SetField(checkresult.FieldDiffChanged, field.TypeBool, value)
		_node.DiffChanged = value
	}
	if value, ok := _c.mutation.DiffKind(); ok {
		_spec.SetField(checkresult.FieldDiffKind, field.TypeString, value)
		_node.DiffKind = &value
	}
	if value, ok := _c.mutation.DiffSummary(); ok {
		_spec.SetField(checkresult.FieldDiffSummary, field.TypeString, value)
		_node.DiffSummary = &value
	}
	if value, ok := _c.mutation.DiffDetails(); ok {
		_spec.SetField(checkresult.FieldDiffDetails, field.TypeString, value)
		_node.DiffDetails = &value
	}
	if value, ok := _c.mutation.CheckedAt(); ok {
		_spec.SetField(checkresult.FieldCheckedAt, field.TypeTime, value)
		_node.CheckedAt = value
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.MonitorTable,
			Columns: []string{checkresult.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.monitor_check_results = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheckResultCreateBulk is the builder for creating many CheckResult entities in bulk.
type CheckResultCreateBulk struct {
	config
	err      error
	builders []*CheckResultCreate
}

// Save creates the CheckResult entities in the database.
func (_c *CheckResultCreateBulk) Save(ctx context.Context) ([]*CheckResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckResultCreateBulk) SaveX(ctx context.Context) []*CheckResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
