// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/monitor"
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckResultUpdate is the builder for updating CheckResult entities.
type CheckResultUpdate struct {
	config
	hooks    []Hook
	mutation *CheckResultMutation
}

// Where appends a list predicates to the CheckResultUpdate builder.
func (_u *CheckResultUpdate) Where(ps ...predicate.CheckResult) *CheckResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CheckResultUpdate) SetStatus(v string) *CheckResultUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableStatus(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *CheckResultUpdate) SetStatusCode(v int) *CheckResultUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableStatusCode(v *int) *CheckResultUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *CheckResultUpdate) AddStatusCode(v int) *CheckResultUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *CheckResultUpdate) ClearStatusCode() *CheckResultUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *CheckResultUpdate) SetResponseTimeMs(v int) *CheckResultUpdate {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableResponseTimeMs(v *int) *CheckResultUpdate {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *CheckResultUpdate) AddResponseTimeMs(v int) *CheckResultUpdate {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *CheckResultUpdate) ClearResponseTimeMs() *CheckResultUpdate {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CheckResultUpdate) SetErrorMessage(v string) *CheckResultUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableErrorMessage(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CheckResultUpdate) ClearErrorMessage() *CheckResultUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSelectionType sets the "selection_type" field.
func (_u *CheckResultUpdate) SetSelectionType(v string) *CheckResultUpdate {
	_u.mutation.SetSelectionType(v)
	return _u
}

// SetNillableSelectionType sets the "selection_type" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableSelectionType(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetSelectionType(*v)
	}
	return _u
}

// ClearSelectionType clears the value of the "selection_type" field.
func (_u *CheckResultUpdate) ClearSelectionType() *CheckResultUpdate {
	_u.mutation.ClearSelectionType()
	return _u
}

// SetSelectionValue sets the "selection_value" field.
func (_u *CheckResultUpdate) SetSelectionValue(v string) *CheckResultUpdate {
	_u.mutation.SetSelectionValue(v)
	return _u
}

// SetNillableSelectionValue sets the "selection_value" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableSelectionValue(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetSelectionValue(*v)
	}
	return _u
}

// ClearSelectionValue clears the value of the "selection_value" field.
func (_u *CheckResultUpdate) ClearSelectionValue() *CheckResultUpdate {
	_u.mutation.ClearSelectionValue()
	return _u
}

// SetDiffChanged sets the "diff_changed" field.
func (_u *CheckResultUpdate) SetDiffChanged(v bool) *CheckResultUpdate {
	_u.mutation.SetDiffChanged(v)
	return _u
}

// SetNillableDiffChanged sets the "diff_changed" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableDiffChanged(v *bool) *CheckResultUpdate {
	if v != nil {
		_u.SetDiffChanged(*v)
	}
	return _u
}

// SetDiffKind sets the "diff_kind" field.
func (_u *CheckResultUpdate) SetDiffKind(v string) *CheckResultUpdate {
	_u.mutation.SetDiffKind(v)
	return _u
}

// SetNillableDiffKind sets the "diff_kind" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableDiffKind(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetDiffKind(*v)
	}
	return _u
}

// ClearDiffKind clears the value of the "diff_kind" field.
func (_u *CheckResultUpdate) ClearDiffKind() *CheckResultUpdate {
	_u.mutation.ClearDiffKind()
	return _u
}

// SetDiffSummary sets the "diff_summary" field.
func (_u *CheckResultUpdate) SetDiffSummary(v string) *CheckResultUpdate {
	_u.mutation.SetDiffSummary(v)
	return _u
}

// SetNillableDiffSummary sets the "diff_summary" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableDiffSummary(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetDiffSummary(*v)
	}
	return _u
}

// ClearDiffSummary clears the value of the "diff_summary" field.
func (_u *CheckResultUpdate) ClearDiffSummary() *CheckResultUpdate {
	_u.mutation.ClearDiffSummary()
	return _u
}

// SetDiffDetails sets the "diff_details" field.
func (_u *CheckResultUpdate) SetDiffDetails(v string) *CheckResultUpdate {
	_u.mutation.SetDiffDetails(v)
	return _u
}

// SetNillableDiffDetails sets the "diff_details" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableDiffDetails(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetDiffDetails(*v)
	}
	return _u
}

// ClearDiffDetails clears the value of the "diff_details" field.
func (_u *CheckResultUpdate) ClearDiffDetails() *CheckResultUpdate {
	_u.mutation.ClearDiffDetails()
	return _u
}

// SetCheckedAt sets the "checked_at" field.
func (_u *CheckResultUpdate) SetCheckedAt(v time.Time) *CheckResultUpdate {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableCheckedAt(v *time.Time) *CheckResultUpdate {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// SetMonitorID sets the "monitor" edge to the Monitor entity by ID.
func (_u *CheckResultUpdate) SetMonitorID(id int) *CheckResultUpdate {
	_u.mutation.SetMonitorID(id)
	return _u
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (_u *CheckResultUpdate) SetMonitor(v *Monitor) *CheckResultUpdate {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the CheckResultMutation object of the builder.
func (_u *CheckResultUpdate) Mutation() *CheckResultMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (_u *CheckResultUpdate) ClearMonitor() *CheckResultUpdate {
	_u.mutation.ClearMonitor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckResultUpdate) check() error {
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.monitor"`)
	}
	return nil
}

func (_u *CheckResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkresult.Table, checkresult.Columns, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(checkresult.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(checkresult.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(checkresult.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(checkresult.FieldResponseTimeMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(checkresult.FieldResponseTimeMs, field.TypeInt, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(checkresult.FieldResponseTimeMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(checkresult.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(checkresult.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SelectionType(); ok {
		_spec.SetField(checkresult.FieldSelectionType, field.TypeString, value)
	}
	if _u.mutation.SelectionTypeCleared() {
		_spec.ClearField(checkresult.FieldSelectionType, field.TypeString)
	}
	if value, ok := _u.mutation.SelectionValue(); ok {
		_spec.SetField(checkresult.FieldSelectionValue, field.TypeString, value)
	}
	if _u.mutation.SelectionValueCleared() {
		_spec.ClearField(checkresult.FieldSelectionValue, field.TypeString)
	}
	if value, ok := _u.mutation.DiffChanged(); ok {
		_spec.SetField(checkresult.FieldDiffChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DiffKind(); ok {
		_spec.SetField(checkresult.FieldDiffKind, field.TypeString, value)
	}
	if _u.mutation.DiffKindCleared() {
		_spec.ClearField(checkresult.FieldDiffKind, field.TypeString)
	}
	if value, ok := _u.mutation.DiffSummary(); ok {
		_spec.SetField(checkresult.FieldDiffSummary, field.TypeString, value)
	}
	if _u.mutation.DiffSummaryCleared() {
		_spec.ClearField(checkresult.FieldDiffSummary, field.TypeString)
	}
	if value, ok := _u.mutation.DiffDetails(); ok {
		_spec.SetField(checkresult.FieldDiffDetails, field.TypeString, value)
	}
	if _u.mutation.DiffDetailsCleared() {
		_spec.ClearField(checkresult.FieldDiffDetails, field.TypeString)
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(checkresult.FieldCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.MonitorTable,
			Columns: []string{checkresult.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.MonitorTable,
			Columns: []string{checkresult.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckResultUpdateOne is the builder for updating a single CheckResult entity.
type CheckResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckResultMutation
}

// SetStatus sets the "status" field.
func (_u *CheckResultUpdateOne) SetStatus(v string) *CheckResultUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableStatus(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *CheckResultUpdateOne) SetStatusCode(v int) *CheckResultUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableStatusCode(v *int) *CheckResultUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *CheckResultUpdateOne) AddStatusCode(v int) *CheckResultUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *CheckResultUpdateOne) ClearStatusCode() *CheckResultUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *CheckResultUpdateOne) SetResponseTimeMs(v int) *CheckResultUpdateOne {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableResponseTimeMs(v *int) *CheckResultUpdateOne {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *CheckResultUpdateOne) AddResponseTimeMs(v int) *CheckResultUpdateOne {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *CheckResultUpdateOne) ClearResponseTimeMs() *CheckResultUpdateOne {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CheckResultUpdateOne) SetErrorMessage(v string) *CheckResultUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableErrorMessage(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CheckResultUpdateOne) ClearErrorMessage() *CheckResultUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSelectionType sets the "selection_type" field.
func (_u *CheckResultUpdateOne) SetSelectionType(v string) *CheckResultUpdateOne {
	_u.mutation.SetSelectionType(v)
	return _u
}

// SetNillableSelectionType sets the "selection_type" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableSelectionType(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetSelectionType(*v)
	}
	return _u
}

// ClearSelectionType clears the value of the "selection_type" field.
func (_u *CheckResultUpdateOne) ClearSelectionType() *CheckResultUpdateOne {
	_u.mutation.ClearSelectionType()
	return _u
}

// SetSelectionValue sets the "selection_value" field.
func (_u *CheckResultUpdateOne) SetSelectionValue(v string) *CheckResultUpdateOne {
	_u.mutation.SetSelectionValue(v)
	return _u
}

// SetNillableSelectionValue sets the "selection_value" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableSelectionValue(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetSelectionValue(*v)
	}
	return _u
}

// ClearSelectionValue clears the value of the "selection_value" field.
func (_u *CheckResultUpdateOne) ClearSelectionValue() *CheckResultUpdateOne {
	_u.mutation.ClearSelectionValue()
	return _u
}

// SetDiffChanged sets the "diff_changed" field.
func (_u *CheckResultUpdateOne) SetDiffChanged(v bool) *CheckResultUpdateOne {
	_u.mutation.SetDiffChanged(v)
	return _u
}

// SetNillableDiffChanged sets the "diff_changed" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableDiffChanged(v *bool) *CheckResultUpdateOne {
	if v != nil {
		_u.SetDiffChanged(*v)
	}
	return _u
}

// SetDiffKind sets the "diff_kind" field.
func (_u *CheckResultUpdateOne) SetDiffKind(v string) *CheckResultUpdateOne {
	_u.mutation.SetDiffKind(v)
	return _u
}

// SetNillableDiffKind sets the "diff_kind" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableDiffKind(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetDiffKind(*v)
	}
	return _u
}

// ClearDiffKind clears the value of the "diff_kind" field.
func (_u *CheckResultUpdateOne) ClearDiffKind() *CheckResultUpdateOne {
	_u.mutation.ClearDiffKind()
	return _u
}

// SetDiffSummary sets the "diff_summary" field.
func (_u *CheckResultUpdateOne) SetDiffSummary(v string) *CheckResultUpdateOne {
	_u.mutation.SetDiffSummary(v)
	return _u
}

// SetNillableDiffSummary sets the "diff_summary" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableDiffSummary(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetDiffSummary(*v)
	}
	return _u
}

// ClearDiffSummary clears the value of the "diff_summary" field.
func (_u *CheckResultUpdateOne) ClearDiffSummary() *CheckResultUpdateOne {
	_u.mutation.ClearDiffSummary()
	return _u
}

// SetDiffDetails sets the "diff_details" field.
func (_u *CheckResultUpdateOne) SetDiffDetails(v string) *CheckResultUpdateOne {
	_u.mutation.SetDiffDetails(v)
	return _u
}

// SetNillableDiffDetails sets the "diff_details" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableDiffDetails(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetDiffDetails(*v)
	}
	return _u
}

// ClearDiffDetails clears the value of the "diff_details" field.
func (_u *CheckResultUpdateOne) ClearDiffDetails() *CheckResultUpdateOne {
	_u.mutation.ClearDiffDetails()
	return _u
}

// SetCheckedAt sets the "checked_at" field.
func (_u *CheckResultUpdateOne) SetCheckedAt(v time.Time) *CheckResultUpdateOne {
	_u.mutation.SetCheckedAt(v)
	return _u
}

// SetNillableCheckedAt sets the "checked_at" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableCheckedAt(v *time.Time) *CheckResultUpdateOne {
	if v != nil {
		_u.SetCheckedAt(*v)
	}
	return _u
}

// SetMonitorID sets the "monitor" edge to the Monitor entity by ID.
func (_u *CheckResultUpdateOne) SetMonitorID(id int) *CheckResultUpdateOne {
	_u.mutation.SetMonitorID(id)
	return _u
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (_u *CheckResultUpdateOne) SetMonitor(v *Monitor) *CheckResultUpdateOne {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the CheckResultMutation object of the builder.
func (_u *CheckResultUpdateOne) Mutation() *CheckResultMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (_u *CheckResultUpdateOne) ClearMonitor() *CheckResultUpdateOne {
	_u.mutation.ClearMonitor()
	return _u
}

// Where appends a list predicates to the CheckResultUpdate builder.
func (_u *CheckResultUpdateOne) Where(ps ...predicate.CheckResult) *CheckResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckResultUpdateOne) Select(field string, fields ...string) *CheckResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckResult entity.
func (_u *CheckResultUpdateOne) Save(ctx context.Context) (*CheckResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckResultUpdateOne) SaveX(ctx context.Context) *CheckResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckResultUpdateOne) check() error {
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.monitor"`)
	}
	return nil
}

func (_u *CheckResultUpdateOne) sqlSave(ctx context.Context) (_node *CheckResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkresult.Table, checkresult.Columns, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkresult.FieldID)
		for _, f := range fields {
			if !checkresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(checkresult.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(checkresult.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(checkresult.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(checkresult.FieldResponseTimeMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(checkresult.FieldResponseTimeMs, field.TypeInt, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(checkresult.FieldResponseTimeMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(checkresult.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(checkresult.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SelectionType(); ok {
		_spec.SetField(checkresult.FieldSelectionType, field.TypeString, value)
	}
	if _u.mutation.SelectionTypeCleared() {
		_spec.ClearField(checkresult.FieldSelectionType, field.TypeString)
	}
	if value, ok := _u.mutation.SelectionValue(); ok {
		_spec.SetField(checkresult.FieldSelectionValue, field.TypeString, value)
	}
	if _u.mutation.SelectionValueCleared() {
		_spec.ClearField(checkresult.FieldSelectionValue, field.TypeString)
	}
	if value, ok := _u.mutation.DiffChanged(); ok {
		_spec.SetField(checkresult.FieldDiffChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DiffKind(); ok {
		_spec.SetField(checkresult.FieldDiffKind, field.TypeString, value)
	}
	if _u.mutation.DiffKindCleared() {
		_spec.ClearField(checkresult.FieldDiffKind, field.TypeString)
	}
	if value, ok := _u.mutation.DiffSummary(); ok {
		_spec.SetField(checkresult.FieldDiffSummary, field.TypeString, value)
	}
	if _u.mutation.DiffSummaryCleared() {
		_spec.ClearField(checkresult.FieldDiffSummary, field.TypeString)
	}
	if value, ok := _u.mutation.DiffDetails(); ok {
		_spec.SetField(checkresult.FieldDiffDetails, field.TypeString, value)
	}
	if _u.mutation.DiffDetailsCleared() {
		_spec.ClearField(checkresult.FieldDiffDetails, field.TypeString)
	}
	if value, ok := _u.mutation.CheckedAt(); ok {
		_spec.SetField(checkresult.FieldCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.MonitorTable,
			Columns: []string{checkresult.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.MonitorTable,
			Columns: []string{checkresult.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
