// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckResultQuery is the builder for querying CheckResult entities.
type CheckResultQuery struct {
	config
	ctx          *QueryContext
	order        []checkresult.OrderOption
	inters       []Interceptor
	predicates   []predicate.CheckResult
	withEndpoint *EndpointQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CheckResultQuery builder.
func (_q *CheckResultQuery) Where(ps ...predicate.CheckResult) *CheckResultQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CheckResultQuery) Limit(limit int) *CheckResultQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CheckResultQuery) Offset(offset int) *CheckResultQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CheckResultQuery) Unique(unique bool) *CheckResultQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CheckResultQuery) Order(o ...checkresult.OrderOption) *CheckResultQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEndpoint chains the current query on the "endpoint" edge.
func (_q *CheckResultQuery) QueryEndpoint() *EndpointQuery {
	query := (&EndpointClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checkresult.Table, checkresult.FieldID, selector),
			sqlgraph.To(endpoint.Table, endpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkresult.EndpointTable, checkresult.EndpointColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CheckResult entity from the query.
// Returns a *NotFoundError when no CheckResult was found.
func (_q *CheckResultQuery) First(ctx context.Context) (*CheckResult, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{checkresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CheckResultQuery) FirstX(ctx context.Context) *CheckResult {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CheckResult ID from the query.
// Returns a *NotFoundError when no CheckResult ID was found.
func (_q *CheckResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{checkresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CheckResultQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CheckResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CheckResult entity is found.
// Returns a *NotFoundError when no CheckResult entities are found.
func (_q *CheckResultQuery) Only(ctx context.Context) (*CheckResult, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{checkresult.Label}
	default:
		return nil, &NotSingularError{checkresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CheckResultQuery) OnlyX(ctx context.Context) *CheckResult {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CheckResult ID in the query.
// Returns a *NotSingularError when more than one CheckResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CheckResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{checkresult.Label}
	default:
		err = &NotSingularError{checkresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CheckResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CheckResults.
func (_q *CheckResultQuery) All(ctx context.Context) ([]*CheckResult, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CheckResult, *CheckResultQuery]()
	return withInterceptors[[]*CheckResult](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CheckResultQuery) AllX(ctx context.Context) []*CheckResult {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CheckResult IDs.
func (_q *CheckResultQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(checkresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CheckResultQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CheckResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CheckResultQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CheckResultQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CheckResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CheckResultQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CheckResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CheckResultQuery) Clone() *CheckResultQuery {
	if _q == nil {
		return nil
	}
	return &CheckResultQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]checkresult.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.CheckResult{}, _q.predicates...),
		withEndpoint: _q.withEndpoint.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEndpoint tells the query-builder to eager-load the nodes that are connected to
// the "endpoint" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CheckResultQuery) WithEndpoint(opts ...func(*EndpointQuery)) *CheckResultQuery {
	query := (&EndpointClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEndpoint = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CheckResult.Query().
//		GroupBy(checkresult.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CheckResultQuery) GroupBy(field string, fields ...string) *CheckResultGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CheckResultGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = checkresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.CheckResult.Query().
//		Select(checkresult.FieldStatus).
//		Scan(ctx, &v)
func (_q *CheckResultQuery) Select(fields ...string) *CheckResultSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CheckResultSelect{CheckResultQuery: _q}
	sbuild.label = checkresult.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CheckResultSelect configured with the given aggregations.
func (_q *CheckResultQuery) Aggregate(fns ...AggregateFunc) *CheckResultSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CheckResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !checkresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CheckResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CheckResult, error) {
	var (
		nodes       = []*CheckResult{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withEndpoint != nil,
		}
	)
	if _q.withEndpoint != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, checkresult.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CheckResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CheckResult{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEndpoint; query != nil {
		if err := _q.loadEndpoint(ctx, query, nodes, nil,
			func(n *CheckResult, e *Endpoint) { n.Edges.Endpoint = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CheckResultQuery) loadEndpoint(ctx context.Context, query *EndpointQuery, nodes []*CheckResult, init func(*CheckResult), assign func(*CheckResult, *Endpoint)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CheckResult)
	for i := range nodes {
		if nodes[i].endpoint_check_results == nil {
			continue
		}
		fk := *nodes[i].endpoint_check_results
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(endpoint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "endpoint_check_results" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CheckResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CheckResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(checkresult.Table, checkresult.Columns, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkresult.FieldID)
		for i := range fields {
			if fields[i] != checkresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CheckResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(checkresult.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = checkresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CheckResultGroupBy is the group-by builder for CheckResult entities.
type CheckResultGroupBy struct {
	selector
	build *CheckResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CheckResultGroupBy) Aggregate(fns ...AggregateFunc) *CheckResultGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CheckResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckResultQuery, *CheckResultGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CheckResultGroupBy) sqlScan(ctx context.Context, root *CheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CheckResultSelect is the builder for selecting fields of CheckResult entities.
type CheckResultSelect struct {
	*CheckResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CheckResultSelect) Aggregate(fns ...AggregateFunc) *CheckResultSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CheckResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckResultQuery, *CheckResultSelect](ctx, _s.CheckResultQuery, _s, _s.inters, v)
}

func (_s *CheckResultSelect) sqlScan(ctx context.Context, root *CheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
