// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CheckResult is the model entity for the CheckResult schema.
type CheckResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// ResponseTimeMs holds the value of the "response_time_ms" field.
	ResponseTimeMs *int `json:"response_time_ms,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckResultQuery when eager-loading is set.
	Edges                  CheckResultEdges `json:"edges"`
	endpoint_check_results *int
	selectValues           sql.SelectValues
}

// CheckResultEdges holds the relations/edges for other nodes in the graph.
type CheckResultEdges struct {
	// Endpoint holds the value of the endpoint edge.
	Endpoint *Endpoint `json:"endpoint,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EndpointOrErr returns the Endpoint value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckResultEdges) EndpointOrErr() (*Endpoint, error) {
	if e.Endpoint != nil {
		return e.Endpoint, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: endpoint.Label}
	}
	return nil, &NotLoadedError{edge: "endpoint"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkresult.FieldID, checkresult.FieldStatusCode, checkresult.FieldResponseTimeMs:
			values[i] = new(sql.NullInt64)
		case checkresult.FieldStatus, checkresult.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case checkresult.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		case checkresult.ForeignKeys[0]: // endpoint_check_results
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckResult fields.
func (_m *CheckResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case checkresult.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case checkresult.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case checkresult.FieldResponseTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_time_ms", values[i])
			} else if value.Valid {
				_m.ResponseTimeMs = new(int)
				*_m.ResponseTimeMs = int(value.Int64)
			}
		case checkresult.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case checkresult.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		case checkresult.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field endpoint_check_results", value)
			} else if value.Valid {
				_m.endpoint_check_results = new(int)
				*_m.endpoint_check_results = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckResult.
// This includes values selected through modifiers, order, etc.
func (_m *CheckResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEndpoint queries the "endpoint" edge of the CheckResult entity.
func (_m *CheckResult) QueryEndpoint() *EndpointQuery {
	return NewCheckResultClient(_m.config).QueryEndpoint(_m)
}

// Update returns a builder for updating this CheckResult.
// Note that you need to call CheckResult.Unwrap() before calling this method if this CheckResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckResult) Update() *CheckResultUpdateOne {
	return NewCheckResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckResult) Unwrap() *CheckResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckResult) String() string {
	var builder strings.Builder
	builder.WriteString("CheckResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResponseTimeMs; v != nil {
		builder.WriteString("response_time_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckResults is a parsable slice of CheckResult.
type CheckResults []*CheckResult
