// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"goanna/apps/api/ent/migrate"

	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationchannel"
	"goanna/apps/api/ent/notificationevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CheckResult is the client for interacting with the CheckResult builders.
	CheckResult *CheckResultClient
	// Endpoint is the client for interacting with the Endpoint builders.
	Endpoint *EndpointClient
	// NotificationChannel is the client for interacting with the NotificationChannel builders.
	NotificationChannel *NotificationChannelClient
	// NotificationEvent is the client for interacting with the NotificationEvent builders.
	NotificationEvent *NotificationEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CheckResult = NewCheckResultClient(c.config)
	c.Endpoint = NewEndpointClient(c.config)
	c.NotificationChannel = NewNotificationChannelClient(c.config)
	c.NotificationEvent = NewNotificationEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		CheckResult:         NewCheckResultClient(cfg),
		Endpoint:            NewEndpointClient(cfg),
		NotificationChannel: NewNotificationChannelClient(cfg),
		NotificationEvent:   NewNotificationEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		CheckResult:         NewCheckResultClient(cfg),
		Endpoint:            NewEndpointClient(cfg),
		NotificationChannel: NewNotificationChannelClient(cfg),
		NotificationEvent:   NewNotificationEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CheckResult.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CheckResult.Use(hooks...)
	c.Endpoint.Use(hooks...)
	c.NotificationChannel.Use(hooks...)
	c.NotificationEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CheckResult.Intercept(interceptors...)
	c.Endpoint.Intercept(interceptors...)
	c.NotificationChannel.Intercept(interceptors...)
	c.NotificationEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CheckResultMutation:
		return c.CheckResult.mutate(ctx, m)
	case *EndpointMutation:
		return c.Endpoint.mutate(ctx, m)
	case *NotificationChannelMutation:
		return c.NotificationChannel.mutate(ctx, m)
	case *NotificationEventMutation:
		return c.NotificationEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CheckResultClient is a client for the CheckResult schema.
type CheckResultClient struct {
	config
}

// NewCheckResultClient returns a client for the CheckResult from the given config.
func NewCheckResultClient(c config) *CheckResultClient {
	return &CheckResultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `checkresult.Hooks(f(g(h())))`.
func (c *CheckResultClient) Use(hooks ...Hook) {
	c.hooks.CheckResult = append(c.hooks.CheckResult, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `checkresult.Intercept(f(g(h())))`.
func (c *CheckResultClient) Intercept(interceptors ...Interceptor) {
	c.inters.CheckResult = append(c.inters.CheckResult, interceptors...)
}

// Create returns a builder for creating a CheckResult entity.
func (c *CheckResultClient) Create() *CheckResultCreate {
	mutation := newCheckResultMutation(c.config, OpCreate)
	return &CheckResultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CheckResult entities.
func (c *CheckResultClient) CreateBulk(builders ...*CheckResultCreate) *CheckResultCreateBulk {
	return &CheckResultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CheckResultClient) MapCreateBulk(slice any, setFunc func(*CheckResultCreate, int)) *CheckResultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CheckResultCreateBulk{err: fmt.Errorf("calling to CheckResultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CheckResultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CheckResultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CheckResult.
func (c *CheckResultClient) Update() *CheckResultUpdate {
	mutation := newCheckResultMutation(c.config, OpUpdate)
	return &CheckResultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CheckResultClient) UpdateOne(_m *CheckResult) *CheckResultUpdateOne {
	mutation := newCheckResultMutation(c.config, OpUpdateOne, withCheckResult(_m))
	return &CheckResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CheckResultClient) UpdateOneID(id int) *CheckResultUpdateOne {
	mutation := newCheckResultMutation(c.config, OpUpdateOne, withCheckResultID(id))
	return &CheckResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CheckResult.
func (c *CheckResultClient) Delete() *CheckResultDelete {
	mutation := newCheckResultMutation(c.config, OpDelete)
	return &CheckResultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CheckResultClient) DeleteOne(_m *CheckResult) *CheckResultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CheckResultClient) DeleteOneID(id int) *CheckResultDeleteOne {
	builder := c.Delete().Where(checkresult.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CheckResultDeleteOne{builder}
}

// Query returns a query builder for CheckResult.
func (c *CheckResultClient) Query() *CheckResultQuery {
	return &CheckResultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCheckResult},
		inters: c.Interceptors(),
	}
}

// Get returns a CheckResult entity by its id.
func (c *CheckResultClient) Get(ctx context.Context, id int) (*CheckResult, error) {
	return c.Query().Where(checkresult.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CheckResultClient) GetX(ctx context.Context, id int) *CheckResult {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEndpoint queries the endpoint edge of a CheckResult.
func (c *CheckResultClient) QueryEndpoint(_m *CheckResult) *EndpointQuery {
	query := (&EndpointClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(checkresult.Table, checkresult.FieldID, id),
			sqlgraph.To(endpoint.Table, endpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkresult.EndpointTable, checkresult.EndpointColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CheckResultClient) Hooks() []Hook {
	return c.hooks.CheckResult
}

// Interceptors returns the client interceptors.
func (c *CheckResultClient) Interceptors() []Interceptor {
	return c.inters.CheckResult
}

func (c *CheckResultClient) mutate(ctx context.Context, m *CheckResultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CheckResultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CheckResultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CheckResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CheckResultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CheckResult mutation op: %q", m.Op())
	}
}

// EndpointClient is a client for the Endpoint schema.
type EndpointClient struct {
	config
}

// NewEndpointClient returns a client for the Endpoint from the given config.
func NewEndpointClient(c config) *EndpointClient {
	return &EndpointClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `endpoint.Hooks(f(g(h())))`.
func (c *EndpointClient) Use(hooks ...Hook) {
	c.hooks.Endpoint = append(c.hooks.Endpoint, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `endpoint.Intercept(f(g(h())))`.
func (c *EndpointClient) Intercept(interceptors ...Interceptor) {
	c.inters.Endpoint = append(c.inters.Endpoint, interceptors...)
}

// Create returns a builder for creating a Endpoint entity.
func (c *EndpointClient) Create() *EndpointCreate {
	mutation := newEndpointMutation(c.config, OpCreate)
	return &EndpointCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Endpoint entities.
func (c *EndpointClient) CreateBulk(builders ...*EndpointCreate) *EndpointCreateBulk {
	return &EndpointCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EndpointClient) MapCreateBulk(slice any, setFunc func(*EndpointCreate, int)) *EndpointCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EndpointCreateBulk{err: fmt.Errorf("calling to EndpointClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EndpointCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EndpointCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Endpoint.
func (c *EndpointClient) Update() *EndpointUpdate {
	mutation := newEndpointMutation(c.config, OpUpdate)
	return &EndpointUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EndpointClient) UpdateOne(_m *Endpoint) *EndpointUpdateOne {
	mutation := newEndpointMutation(c.config, OpUpdateOne, withEndpoint(_m))
	return &EndpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EndpointClient) UpdateOneID(id int) *EndpointUpdateOne {
	mutation := newEndpointMutation(c.config, OpUpdateOne, withEndpointID(id))
	return &EndpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Endpoint.
func (c *EndpointClient) Delete() *EndpointDelete {
	mutation := newEndpointMutation(c.config, OpDelete)
	return &EndpointDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EndpointClient) DeleteOne(_m *Endpoint) *EndpointDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EndpointClient) DeleteOneID(id int) *EndpointDeleteOne {
	builder := c.Delete().Where(endpoint.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EndpointDeleteOne{builder}
}

// Query returns a query builder for Endpoint.
func (c *EndpointClient) Query() *EndpointQuery {
	return &EndpointQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEndpoint},
		inters: c.Interceptors(),
	}
}

// Get returns a Endpoint entity by its id.
func (c *EndpointClient) Get(ctx context.Context, id int) (*Endpoint, error) {
	return c.Query().Where(endpoint.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EndpointClient) GetX(ctx context.Context, id int) *Endpoint {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCheckResults queries the check_results edge of a Endpoint.
func (c *EndpointClient) QueryCheckResults(_m *Endpoint) *CheckResultQuery {
	query := (&CheckResultClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(endpoint.Table, endpoint.FieldID, id),
			sqlgraph.To(checkresult.Table, checkresult.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, endpoint.CheckResultsTable, endpoint.CheckResultsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNotificationEvents queries the notification_events edge of a Endpoint.
func (c *EndpointClient) QueryNotificationEvents(_m *Endpoint) *NotificationEventQuery {
	query := (&NotificationEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(endpoint.Table, endpoint.FieldID, id),
			sqlgraph.To(notificationevent.Table, notificationevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, endpoint.NotificationEventsTable, endpoint.NotificationEventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EndpointClient) Hooks() []Hook {
	return c.hooks.Endpoint
}

// Interceptors returns the client interceptors.
func (c *EndpointClient) Interceptors() []Interceptor {
	return c.inters.Endpoint
}

func (c *EndpointClient) mutate(ctx context.Context, m *EndpointMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EndpointCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EndpointUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EndpointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EndpointDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Endpoint mutation op: %q", m.Op())
	}
}

// NotificationChannelClient is a client for the NotificationChannel schema.
type NotificationChannelClient struct {
	config
}

// NewNotificationChannelClient returns a client for the NotificationChannel from the given config.
func NewNotificationChannelClient(c config) *NotificationChannelClient {
	return &NotificationChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notificationchannel.Hooks(f(g(h())))`.
func (c *NotificationChannelClient) Use(hooks ...Hook) {
	c.hooks.NotificationChannel = append(c.hooks.NotificationChannel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notificationchannel.Intercept(f(g(h())))`.
func (c *NotificationChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotificationChannel = append(c.inters.NotificationChannel, interceptors...)
}

// Create returns a builder for creating a NotificationChannel entity.
func (c *NotificationChannelClient) Create() *NotificationChannelCreate {
	mutation := newNotificationChannelMutation(c.config, OpCreate)
	return &NotificationChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotificationChannel entities.
func (c *NotificationChannelClient) CreateBulk(builders ...*NotificationChannelCreate) *NotificationChannelCreateBulk {
	return &NotificationChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationChannelClient) MapCreateBulk(slice any, setFunc func(*NotificationChannelCreate, int)) *NotificationChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationChannelCreateBulk{err: fmt.Errorf("calling to NotificationChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotificationChannel.
func (c *NotificationChannelClient) Update() *NotificationChannelUpdate {
	mutation := newNotificationChannelMutation(c.config, OpUpdate)
	return &NotificationChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationChannelClient) UpdateOne(_m *NotificationChannel) *NotificationChannelUpdateOne {
	mutation := newNotificationChannelMutation(c.config, OpUpdateOne, withNotificationChannel(_m))
	return &NotificationChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationChannelClient) UpdateOneID(id int) *NotificationChannelUpdateOne {
	mutation := newNotificationChannelMutation(c.config, OpUpdateOne, withNotificationChannelID(id))
	return &NotificationChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotificationChannel.
func (c *NotificationChannelClient) Delete() *NotificationChannelDelete {
	mutation := newNotificationChannelMutation(c.config, OpDelete)
	return &NotificationChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationChannelClient) DeleteOne(_m *NotificationChannel) *NotificationChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationChannelClient) DeleteOneID(id int) *NotificationChannelDeleteOne {
	builder := c.Delete().Where(notificationchannel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationChannelDeleteOne{builder}
}

// Query returns a query builder for NotificationChannel.
func (c *NotificationChannelClient) Query() *NotificationChannelQuery {
	return &NotificationChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotificationChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a NotificationChannel entity by its id.
func (c *NotificationChannelClient) Get(ctx context.Context, id int) (*NotificationChannel, error) {
	return c.Query().Where(notificationchannel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationChannelClient) GetX(ctx context.Context, id int) *NotificationChannel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotificationEvents queries the notification_events edge of a NotificationChannel.
func (c *NotificationChannelClient) QueryNotificationEvents(_m *NotificationChannel) *NotificationEventQuery {
	query := (&NotificationEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationchannel.Table, notificationchannel.FieldID, id),
			sqlgraph.To(notificationevent.Table, notificationevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, notificationchannel.NotificationEventsTable, notificationchannel.NotificationEventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotificationChannelClient) Hooks() []Hook {
	return c.hooks.NotificationChannel
}

// Interceptors returns the client interceptors.
func (c *NotificationChannelClient) Interceptors() []Interceptor {
	return c.inters.NotificationChannel
}

func (c *NotificationChannelClient) mutate(ctx context.Context, m *NotificationChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotificationChannel mutation op: %q", m.Op())
	}
}

// NotificationEventClient is a client for the NotificationEvent schema.
type NotificationEventClient struct {
	config
}

// NewNotificationEventClient returns a client for the NotificationEvent from the given config.
func NewNotificationEventClient(c config) *NotificationEventClient {
	return &NotificationEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notificationevent.Hooks(f(g(h())))`.
func (c *NotificationEventClient) Use(hooks ...Hook) {
	c.hooks.NotificationEvent = append(c.hooks.NotificationEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notificationevent.Intercept(f(g(h())))`.
func (c *NotificationEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotificationEvent = append(c.inters.NotificationEvent, interceptors...)
}

// Create returns a builder for creating a NotificationEvent entity.
func (c *NotificationEventClient) Create() *NotificationEventCreate {
	mutation := newNotificationEventMutation(c.config, OpCreate)
	return &NotificationEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotificationEvent entities.
func (c *NotificationEventClient) CreateBulk(builders ...*NotificationEventCreate) *NotificationEventCreateBulk {
	return &NotificationEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationEventClient) MapCreateBulk(slice any, setFunc func(*NotificationEventCreate, int)) *NotificationEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationEventCreateBulk{err: fmt.Errorf("calling to NotificationEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotificationEvent.
func (c *NotificationEventClient) Update() *NotificationEventUpdate {
	mutation := newNotificationEventMutation(c.config, OpUpdate)
	return &NotificationEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationEventClient) UpdateOne(_m *NotificationEvent) *NotificationEventUpdateOne {
	mutation := newNotificationEventMutation(c.config, OpUpdateOne, withNotificationEvent(_m))
	return &NotificationEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationEventClient) UpdateOneID(id int) *NotificationEventUpdateOne {
	mutation := newNotificationEventMutation(c.config, OpUpdateOne, withNotificationEventID(id))
	return &NotificationEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotificationEvent.
func (c *NotificationEventClient) Delete() *NotificationEventDelete {
	mutation := newNotificationEventMutation(c.config, OpDelete)
	return &NotificationEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationEventClient) DeleteOne(_m *NotificationEvent) *NotificationEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationEventClient) DeleteOneID(id int) *NotificationEventDeleteOne {
	builder := c.Delete().Where(notificationevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationEventDeleteOne{builder}
}

// Query returns a query builder for NotificationEvent.
func (c *NotificationEventClient) Query() *NotificationEventQuery {
	return &NotificationEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotificationEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a NotificationEvent entity by its id.
func (c *NotificationEventClient) Get(ctx context.Context, id int) (*NotificationEvent, error) {
	return c.Query().Where(notificationevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationEventClient) GetX(ctx context.Context, id int) *NotificationEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEndpoint queries the endpoint edge of a NotificationEvent.
func (c *NotificationEventClient) QueryEndpoint(_m *NotificationEvent) *EndpointQuery {
	query := (&EndpointClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationevent.Table, notificationevent.FieldID, id),
			sqlgraph.To(endpoint.Table, endpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notificationevent.EndpointTable, notificationevent.EndpointColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannel queries the channel edge of a NotificationEvent.
func (c *NotificationEventClient) QueryChannel(_m *NotificationEvent) *NotificationChannelQuery {
	query := (&NotificationChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationevent.Table, notificationevent.FieldID, id),
			sqlgraph.To(notificationchannel.Table, notificationchannel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notificationevent.ChannelTable, notificationevent.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotificationEventClient) Hooks() []Hook {
	return c.hooks.NotificationEvent
}

// Interceptors returns the client interceptors.
func (c *NotificationEventClient) Interceptors() []Interceptor {
	return c.inters.NotificationEvent
}

func (c *NotificationEventClient) mutate(ctx context.Context, m *NotificationEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotificationEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CheckResult, Endpoint, NotificationChannel, NotificationEvent []ent.Hook
	}
	inters struct {
		CheckResult, Endpoint, NotificationChannel, NotificationEvent []ent.Interceptor
	}
)
