// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EndpointCreate is the builder for creating a Endpoint entity.
type EndpointCreate struct {
	config
	mutation *EndpointMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *EndpointCreate) SetName(v string) *EndpointCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *EndpointCreate) SetURL(v string) *EndpointCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *EndpointCreate) SetMethod(v string) *EndpointCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableMethod(v *string) *EndpointCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *EndpointCreate) SetIntervalSeconds(v int) *EndpointCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableIntervalSeconds(v *int) *EndpointCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_c *EndpointCreate) SetTimeoutSeconds(v int) *EndpointCreate {
	_c.mutation.SetTimeoutSeconds(v)
	return _c
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableTimeoutSeconds(v *int) *EndpointCreate {
	if v != nil {
		_c.SetTimeoutSeconds(*v)
	}
	return _c
}

// SetExpectedStatus sets the "expected_status" field.
func (_c *EndpointCreate) SetExpectedStatus(v int) *EndpointCreate {
	_c.mutation.SetExpectedStatus(v)
	return _c
}

// SetNillableExpectedStatus sets the "expected_status" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableExpectedStatus(v *int) *EndpointCreate {
	if v != nil {
		_c.SetExpectedStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EndpointCreate) SetCreatedAt(v time.Time) *EndpointCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableCreatedAt(v *time.Time) *EndpointCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EndpointCreate) SetUpdatedAt(v time.Time) *EndpointCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EndpointCreate) SetNillableUpdatedAt(v *time.Time) *EndpointCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddCheckResultIDs adds the "check_results" edge to the CheckResult entity by IDs.
func (_c *EndpointCreate) AddCheckResultIDs(ids ...int) *EndpointCreate {
	_c.mutation.AddCheckResultIDs(ids...)
	return _c
}

// AddCheckResults adds the "check_results" edges to the CheckResult entity.
func (_c *EndpointCreate) AddCheckResults(v ...*CheckResult) *EndpointCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckResultIDs(ids...)
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_c *EndpointCreate) AddNotificationEventIDs(ids ...int) *EndpointCreate {
	_c.mutation.AddNotificationEventIDs(ids...)
	return _c
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_c *EndpointCreate) AddNotificationEvents(v ...*NotificationEvent) *EndpointCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationEventIDs(ids...)
}

// Mutation returns the EndpointMutation object of the builder.
func (_c *EndpointCreate) Mutation() *EndpointMutation {
	return _c.mutation
}

// Save creates the Endpoint in the database.
func (_c *EndpointCreate) Save(ctx context.Context) (*Endpoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EndpointCreate) SaveX(ctx context.Context) *Endpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndpointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndpointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EndpointCreate) defaults() {
	if _, ok := _c.mutation.Method(); !ok {
		v := endpoint.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := endpoint.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.TimeoutSeconds(); !ok {
		v := endpoint.DefaultTimeoutSeconds
		_c.mutation.SetTimeoutSeconds(v)
	}
	if _, ok := _c.mutation.ExpectedStatus(); !ok {
		v := endpoint.DefaultExpectedStatus
		_c.mutation.SetExpectedStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := endpoint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := endpoint.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EndpointCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Endpoint.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := endpoint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Endpoint.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Endpoint.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := endpoint.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Endpoint.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "Endpoint.method"`)}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "Endpoint.interval_seconds"`)}
	}
	if v, ok := _c.mutation.IntervalSeconds(); ok {
		if err := endpoint.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.interval_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeoutSeconds(); !ok {
		return &ValidationError{Name: "timeout_seconds", err: errors.New(`ent: missing required field "Endpoint.timeout_seconds"`)}
	}
	if v, ok := _c.mutation.TimeoutSeconds(); ok {
		if err := endpoint.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.timeout_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedStatus(); !ok {
		return &ValidationError{Name: "expected_status", err: errors.New(`ent: missing required field "Endpoint.expected_status"`)}
	}
	if v, ok := _c.mutation.ExpectedStatus(); ok {
		if err := endpoint.ExpectedStatusValidator(v); err != nil {
			return &ValidationError{Name: "expected_status", err: fmt.Errorf(`ent: validator failed for field "Endpoint.expected_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Endpoint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Endpoint.updated_at"`)}
	}
	return nil
}

func (_c *EndpointCreate) sqlSave(ctx context.Context) (*Endpoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EndpointCreate) createSpec() (*Endpoint, *sqlgraph.CreateSpec) {
	var (
		_node = &Endpoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(endpoint.Table, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(endpoint.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(endpoint.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(endpoint.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(endpoint.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := _c.mutation.TimeoutSeconds(); ok {
		_spec.SetField(endpoint.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = value
	}
	if value, ok := _c.mutation.ExpectedStatus(); ok {
		_spec.SetField(endpoint.FieldExpectedStatus, field.TypeInt, value)
		_node.ExpectedStatus = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(endpoint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(endpoint.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CheckResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EndpointCreateBulk is the builder for creating many Endpoint entities in bulk.
type EndpointCreateBulk struct {
	config
	err      error
	builders []*EndpointCreate
}

// Save creates the Endpoint entities in the database.
func (_c *EndpointCreateBulk) Save(ctx context.Context) ([]*Endpoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Endpoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EndpointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EndpointCreateBulk) SaveX(ctx context.Context) []*Endpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EndpointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EndpointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
