// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationevent"
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EndpointUpdate is the builder for updating Endpoint entities.
type EndpointUpdate struct {
	config
	hooks    []Hook
	mutation *EndpointMutation
}

// Where appends a list predicates to the EndpointUpdate builder.
func (_u *EndpointUpdate) Where(ps ...predicate.Endpoint) *EndpointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *EndpointUpdate) SetName(v string) *EndpointUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableName(v *string) *EndpointUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *EndpointUpdate) SetURL(v string) *EndpointUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableURL(v *string) *EndpointUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *EndpointUpdate) SetMethod(v string) *EndpointUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableMethod(v *string) *EndpointUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *EndpointUpdate) SetIntervalSeconds(v int) *EndpointUpdate {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableIntervalSeconds(v *int) *EndpointUpdate {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *EndpointUpdate) AddIntervalSeconds(v int) *EndpointUpdate {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *EndpointUpdate) SetTimeoutSeconds(v int) *EndpointUpdate {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableTimeoutSeconds(v *int) *EndpointUpdate {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *EndpointUpdate) AddTimeoutSeconds(v int) *EndpointUpdate {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetExpectedStatus sets the "expected_status" field.
func (_u *EndpointUpdate) SetExpectedStatus(v int) *EndpointUpdate {
	_u.mutation.ResetExpectedStatus()
	_u.mutation.SetExpectedStatus(v)
	return _u
}

// SetNillableExpectedStatus sets the "expected_status" field if the given value is not nil.
func (_u *EndpointUpdate) SetNillableExpectedStatus(v *int) *EndpointUpdate {
	if v != nil {
		_u.SetExpectedStatus(*v)
	}
	return _u
}

// AddExpectedStatus adds value to the "expected_status" field.
func (_u *EndpointUpdate) AddExpectedStatus(v int) *EndpointUpdate {
	_u.mutation.AddExpectedStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EndpointUpdate) SetUpdatedAt(v time.Time) *EndpointUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCheckResultIDs adds the "check_results" edge to the CheckResult entity by IDs.
func (_u *EndpointUpdate) AddCheckResultIDs(ids ...int) *EndpointUpdate {
	_u.mutation.AddCheckResultIDs(ids...)
	return _u
}

// AddCheckResults adds the "check_results" edges to the CheckResult entity.
func (_u *EndpointUpdate) AddCheckResults(v ...*CheckResult) *EndpointUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckResultIDs(ids...)
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_u *EndpointUpdate) AddNotificationEventIDs(ids ...int) *EndpointUpdate {
	_u.mutation.AddNotificationEventIDs(ids...)
	return _u
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_u *EndpointUpdate) AddNotificationEvents(v ...*NotificationEvent) *EndpointUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationEventIDs(ids...)
}

// Mutation returns the EndpointMutation object of the builder.
func (_u *EndpointUpdate) Mutation() *EndpointMutation {
	return _u.mutation
}

// ClearCheckResults clears all "check_results" edges to the CheckResult entity.
func (_u *EndpointUpdate) ClearCheckResults() *EndpointUpdate {
	_u.mutation.ClearCheckResults()
	return _u
}

// RemoveCheckResultIDs removes the "check_results" edge to CheckResult entities by IDs.
func (_u *EndpointUpdate) RemoveCheckResultIDs(ids ...int) *EndpointUpdate {
	_u.mutation.RemoveCheckResultIDs(ids...)
	return _u
}

// RemoveCheckResults removes "check_results" edges to CheckResult entities.
func (_u *EndpointUpdate) RemoveCheckResults(v ...*CheckResult) *EndpointUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckResultIDs(ids...)
}

// ClearNotificationEvents clears all "notification_events" edges to the NotificationEvent entity.
func (_u *EndpointUpdate) ClearNotificationEvents() *EndpointUpdate {
	_u.mutation.ClearNotificationEvents()
	return _u
}

// RemoveNotificationEventIDs removes the "notification_events" edge to NotificationEvent entities by IDs.
func (_u *EndpointUpdate) RemoveNotificationEventIDs(ids ...int) *EndpointUpdate {
	_u.mutation.RemoveNotificationEventIDs(ids...)
	return _u
}

// RemoveNotificationEvents removes "notification_events" edges to NotificationEvent entities.
func (_u *EndpointUpdate) RemoveNotificationEvents(v ...*NotificationEvent) *EndpointUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EndpointUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EndpointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EndpointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EndpointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EndpointUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := endpoint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EndpointUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := endpoint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Endpoint.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := endpoint.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Endpoint.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := endpoint.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutSeconds(); ok {
		if err := endpoint.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedStatus(); ok {
		if err := endpoint.ExpectedStatusValidator(v); err != nil {
			return &ValidationError{Name: "expected_status", err: fmt.Errorf(`ent: validator failed for field "Endpoint.expected_status": %w`, err)}
		}
	}
	return nil
}

func (_u *EndpointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(endpoint.Table, endpoint.Columns, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(endpoint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(endpoint.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(endpoint.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(endpoint.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(endpoint.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(endpoint.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(endpoint.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpectedStatus(); ok {
		_spec.SetField(endpoint.FieldExpectedStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpectedStatus(); ok {
		_spec.AddField(endpoint.FieldExpectedStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(endpoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckResultsIDs(); len(nodes) > 0 && !_u.mutation.CheckResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationEventsIDs(); len(nodes) > 0 && !_u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EndpointUpdateOne is the builder for updating a single Endpoint entity.
type EndpointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EndpointMutation
}

// SetName sets the "name" field.
func (_u *EndpointUpdateOne) SetName(v string) *EndpointUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableName(v *string) *EndpointUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *EndpointUpdateOne) SetURL(v string) *EndpointUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableURL(v *string) *EndpointUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *EndpointUpdateOne) SetMethod(v string) *EndpointUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableMethod(v *string) *EndpointUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *EndpointUpdateOne) SetIntervalSeconds(v int) *EndpointUpdateOne {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableIntervalSeconds(v *int) *EndpointUpdateOne {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *EndpointUpdateOne) AddIntervalSeconds(v int) *EndpointUpdateOne {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *EndpointUpdateOne) SetTimeoutSeconds(v int) *EndpointUpdateOne {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableTimeoutSeconds(v *int) *EndpointUpdateOne {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *EndpointUpdateOne) AddTimeoutSeconds(v int) *EndpointUpdateOne {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetExpectedStatus sets the "expected_status" field.
func (_u *EndpointUpdateOne) SetExpectedStatus(v int) *EndpointUpdateOne {
	_u.mutation.ResetExpectedStatus()
	_u.mutation.SetExpectedStatus(v)
	return _u
}

// SetNillableExpectedStatus sets the "expected_status" field if the given value is not nil.
func (_u *EndpointUpdateOne) SetNillableExpectedStatus(v *int) *EndpointUpdateOne {
	if v != nil {
		_u.SetExpectedStatus(*v)
	}
	return _u
}

// AddExpectedStatus adds value to the "expected_status" field.
func (_u *EndpointUpdateOne) AddExpectedStatus(v int) *EndpointUpdateOne {
	_u.mutation.AddExpectedStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EndpointUpdateOne) SetUpdatedAt(v time.Time) *EndpointUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCheckResultIDs adds the "check_results" edge to the CheckResult entity by IDs.
func (_u *EndpointUpdateOne) AddCheckResultIDs(ids ...int) *EndpointUpdateOne {
	_u.mutation.AddCheckResultIDs(ids...)
	return _u
}

// AddCheckResults adds the "check_results" edges to the CheckResult entity.
func (_u *EndpointUpdateOne) AddCheckResults(v ...*CheckResult) *EndpointUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckResultIDs(ids...)
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_u *EndpointUpdateOne) AddNotificationEventIDs(ids ...int) *EndpointUpdateOne {
	_u.mutation.AddNotificationEventIDs(ids...)
	return _u
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_u *EndpointUpdateOne) AddNotificationEvents(v ...*NotificationEvent) *EndpointUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationEventIDs(ids...)
}

// Mutation returns the EndpointMutation object of the builder.
func (_u *EndpointUpdateOne) Mutation() *EndpointMutation {
	return _u.mutation
}

// ClearCheckResults clears all "check_results" edges to the CheckResult entity.
func (_u *EndpointUpdateOne) ClearCheckResults() *EndpointUpdateOne {
	_u.mutation.ClearCheckResults()
	return _u
}

// RemoveCheckResultIDs removes the "check_results" edge to CheckResult entities by IDs.
func (_u *EndpointUpdateOne) RemoveCheckResultIDs(ids ...int) *EndpointUpdateOne {
	_u.mutation.RemoveCheckResultIDs(ids...)
	return _u
}

// RemoveCheckResults removes "check_results" edges to CheckResult entities.
func (_u *EndpointUpdateOne) RemoveCheckResults(v ...*CheckResult) *EndpointUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckResultIDs(ids...)
}

// ClearNotificationEvents clears all "notification_events" edges to the NotificationEvent entity.
func (_u *EndpointUpdateOne) ClearNotificationEvents() *EndpointUpdateOne {
	_u.mutation.ClearNotificationEvents()
	return _u
}

// RemoveNotificationEventIDs removes the "notification_events" edge to NotificationEvent entities by IDs.
func (_u *EndpointUpdateOne) RemoveNotificationEventIDs(ids ...int) *EndpointUpdateOne {
	_u.mutation.RemoveNotificationEventIDs(ids...)
	return _u
}

// RemoveNotificationEvents removes "notification_events" edges to NotificationEvent entities.
func (_u *EndpointUpdateOne) RemoveNotificationEvents(v ...*NotificationEvent) *EndpointUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationEventIDs(ids...)
}

// Where appends a list predicates to the EndpointUpdate builder.
func (_u *EndpointUpdateOne) Where(ps ...predicate.Endpoint) *EndpointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EndpointUpdateOne) Select(field string, fields ...string) *EndpointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Endpoint entity.
func (_u *EndpointUpdateOne) Save(ctx context.Context) (*Endpoint, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EndpointUpdateOne) SaveX(ctx context.Context) *Endpoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EndpointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EndpointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EndpointUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := endpoint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EndpointUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := endpoint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Endpoint.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := endpoint.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Endpoint.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := endpoint.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutSeconds(); ok {
		if err := endpoint.TimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "Endpoint.timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpectedStatus(); ok {
		if err := endpoint.ExpectedStatusValidator(v); err != nil {
			return &ValidationError{Name: "expected_status", err: fmt.Errorf(`ent: validator failed for field "Endpoint.expected_status": %w`, err)}
		}
	}
	return nil
}

func (_u *EndpointUpdateOne) sqlSave(ctx context.Context) (_node *Endpoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(endpoint.Table, endpoint.Columns, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Endpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, endpoint.FieldID)
		for _, f := range fields {
			if !endpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != endpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(endpoint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(endpoint.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(endpoint.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(endpoint.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(endpoint.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(endpoint.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(endpoint.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpectedStatus(); ok {
		_spec.SetField(endpoint.FieldExpectedStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpectedStatus(); ok {
		_spec.AddField(endpoint.FieldExpectedStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(endpoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckResultsIDs(); len(nodes) > 0 && !_u.mutation.CheckResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.CheckResultsTable,
			Columns: []string{endpoint.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationEventsIDs(); len(nodes) > 0 && !_u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   endpoint.NotificationEventsTable,
			Columns: []string{endpoint.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Endpoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
