// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/monitor"
	"goanna/apps/api/ent/monitorruntime"
	"goanna/apps/api/ent/notificationevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitorCreate is the builder for creating a Monitor entity.
type MonitorCreate struct {
	config
	mutation *MonitorMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *MonitorCreate) SetLabel(v string) *MonitorCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableLabel(v *string) *MonitorCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *MonitorCreate) SetMethod(v string) *MonitorCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableMethod(v *string) *MonitorCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MonitorCreate) SetURL(v string) *MonitorCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetIconURL sets the "icon_url" field.
func (_c *MonitorCreate) SetIconURL(v string) *MonitorCreate {
	_c.mutation.SetIconURL(v)
	return _c
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableIconURL(v *string) *MonitorCreate {
	if v != nil {
		_c.SetIconURL(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *MonitorCreate) SetBody(v string) *MonitorCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableBody(v *string) *MonitorCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *MonitorCreate) SetHeaders(v map[string]string) *MonitorCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetAuth sets the "auth" field.
func (_c *MonitorCreate) SetAuth(v map[string]string) *MonitorCreate {
	_c.mutation.SetAuth(v)
	return _c
}

// SetNotificationChannels sets the "notification_channels" field.
func (_c *MonitorCreate) SetNotificationChannels(v []string) *MonitorCreate {
	_c.mutation.SetNotificationChannels(v)
	return _c
}

// SetSelector sets the "selector" field.
func (_c *MonitorCreate) SetSelector(v string) *MonitorCreate {
	_c.mutation.SetSelector(v)
	return _c
}

// SetNillableSelector sets the "selector" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableSelector(v *string) *MonitorCreate {
	if v != nil {
		_c.SetSelector(*v)
	}
	return _c
}

// SetExpectedType sets the "expected_type" field.
func (_c *MonitorCreate) SetExpectedType(v monitor.ExpectedType) *MonitorCreate {
	_c.mutation.SetExpectedType(v)
	return _c
}

// SetNillableExpectedType sets the "expected_type" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableExpectedType(v *monitor.ExpectedType) *MonitorCreate {
	if v != nil {
		_c.SetExpectedType(*v)
	}
	return _c
}

// SetExpectedResponse sets the "expected_response" field.
func (_c *MonitorCreate) SetExpectedResponse(v string) *MonitorCreate {
	_c.mutation.SetExpectedResponse(v)
	return _c
}

// SetNillableExpectedResponse sets the "expected_response" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableExpectedResponse(v *string) *MonitorCreate {
	if v != nil {
		_c.SetExpectedResponse(*v)
	}
	return _c
}

// SetCron sets the "cron" field.
func (_c *MonitorCreate) SetCron(v string) *MonitorCreate {
	_c.mutation.SetCron(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *MonitorCreate) SetEnabled(v bool) *MonitorCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableEnabled(v *bool) *MonitorCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MonitorCreate) SetCreatedAt(v time.Time) *MonitorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableCreatedAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MonitorCreate) SetUpdatedAt(v time.Time) *MonitorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableUpdatedAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddCheckResultIDs adds the "check_results" edge to the CheckResult entity by IDs.
func (_c *MonitorCreate) AddCheckResultIDs(ids ...int) *MonitorCreate {
	_c.mutation.AddCheckResultIDs(ids...)
	return _c
}

// AddCheckResults adds the "check_results" edges to the CheckResult entity.
func (_c *MonitorCreate) AddCheckResults(v ...*CheckResult) *MonitorCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckResultIDs(ids...)
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_c *MonitorCreate) AddNotificationEventIDs(ids ...int) *MonitorCreate {
	_c.mutation.AddNotificationEventIDs(ids...)
	return _c
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_c *MonitorCreate) AddNotificationEvents(v ...*NotificationEvent) *MonitorCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationEventIDs(ids...)
}

// SetRuntimeID sets the "runtime" edge to the MonitorRuntime entity by ID.
func (_c *MonitorCreate) SetRuntimeID(id int) *MonitorCreate {
	_c.mutation.SetRuntimeID(id)
	return _c
}

// SetNillableRuntimeID sets the "runtime" edge to the MonitorRuntime entity by ID if the given value is not nil.
func (_c *MonitorCreate) SetNillableRuntimeID(id *int) *MonitorCreate {
	if id != nil {
		_c = _c.SetRuntimeID(*id)
	}
	return _c
}

// SetRuntime sets the "runtime" edge to the MonitorRuntime entity.
func (_c *MonitorCreate) SetRuntime(v *MonitorRuntime) *MonitorCreate {
	return _c.SetRuntimeID(v.ID)
}

// Mutation returns the MonitorMutation object of the builder.
func (_c *MonitorCreate) Mutation() *MonitorMutation {
	return _c.mutation
}

// Save creates the Monitor in the database.
func (_c *MonitorCreate) Save(ctx context.Context) (*Monitor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MonitorCreate) SaveX(ctx context.Context) *Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MonitorCreate) defaults() {
	if _, ok := _c.mutation.Method(); !ok {
		v := monitor.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.ExpectedType(); !ok {
		v := monitor.DefaultExpectedType
		_c.mutation.SetExpectedType(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := monitor.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := monitor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := monitor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MonitorCreate) check() error {
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "Monitor.method"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Monitor.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := monitor.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Monitor.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedType(); !ok {
		return &ValidationError{Name: "expected_type", err: errors.New(`ent: missing required field "Monitor.expected_type"`)}
	}
	if v, ok := _c.mutation.ExpectedType(); ok {
		if err := monitor.ExpectedTypeValidator(v); err != nil {
			return &ValidationError{Name: "expected_type", err: fmt.Errorf(`ent: validator failed for field "Monitor.expected_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cron(); !ok {
		return &ValidationError{Name: "cron", err: errors.New(`ent: missing required field "Monitor.cron"`)}
	}
	if v, ok := _c.mutation.Cron(); ok {
		if err := monitor.CronValidator(v); err != nil {
			return &ValidationError{Name: "cron", err: fmt.Errorf(`ent: validator failed for field "Monitor.cron": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Monitor.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Monitor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Monitor.updated_at"`)}
	}
	return nil
}

func (_c *MonitorCreate) sqlSave(ctx context.Context) (*Monitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MonitorCreate) createSpec() (*Monitor, *sqlgraph.CreateSpec) {
	var (
		_node = &Monitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(monitor.Table, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(monitor.FieldLabel, field.TypeString, value)
		_node.Label = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(monitor.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(monitor.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.IconURL(); ok {
		_spec.SetField(monitor.FieldIconURL, field.TypeString, value)
		_node.IconURL = &value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(monitor.FieldBody, field.TypeString, value)
		_node.Body = &value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(monitor.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Auth(); ok {
		_spec.SetField(monitor.FieldAuth, field.TypeJSON, value)
		_node.Auth = value
	}
	if value, ok := _c.mutation.NotificationChannels(); ok {
		_spec.SetField(monitor.FieldNotificationChannels, field.TypeJSON, value)
		_node.NotificationChannels = value
	}
	if value, ok := _c.mutation.Selector(); ok {
		_spec.SetField(monitor.FieldSelector, field.TypeString, value)
		_node.Selector = &value
	}
	if value, ok := _c.mutation.ExpectedType(); ok {
		_spec.SetField(monitor.FieldExpectedType, field.TypeEnum, value)
		_node.ExpectedType = value
	}
	if value, ok := _c.mutation.ExpectedResponse(); ok {
		_spec.SetField(monitor.FieldExpectedResponse, field.TypeString, value)
		_node.ExpectedResponse = &value
	}
	if value, ok := _c.mutation.Cron(); ok {
		_spec.SetField(monitor.FieldCron, field.TypeString, value)
		_node.Cron = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(monitor.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(monitor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(monitor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CheckResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.CheckResultsTable,
			Columns: []string{monitor.CheckResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.NotificationEventsTable,
			Columns: []string{monitor.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RuntimeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   monitor.RuntimeTable,
			Columns: []string{monitor.RuntimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitorruntime.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MonitorCreateBulk is the builder for creating many Monitor entities in bulk.
type MonitorCreateBulk struct {
	config
	err      error
	builders []*MonitorCreate
}

// Save creates the Monitor entities in the database.
func (_c *MonitorCreateBulk) Save(ctx context.Context) ([]*Monitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Monitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MonitorCreateBulk) SaveX(ctx context.Context) []*Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
