// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/monitor"
	"goanna/apps/api/ent/monitorruntime"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitorRuntimeCreate is the builder for creating a MonitorRuntime entity.
type MonitorRuntimeCreate struct {
	config
	mutation *MonitorRuntimeMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *MonitorRuntimeCreate) SetStatus(v monitorruntime.Status) *MonitorRuntimeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableStatus(v *monitorruntime.Status) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCheckCount sets the "check_count" field.
func (_c *MonitorRuntimeCreate) SetCheckCount(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetCheckCount(v)
	return _c
}

// SetNillableCheckCount sets the "check_count" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableCheckCount(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetCheckCount(*v)
	}
	return _c
}

// SetSuccessCount sets the "success_count" field.
func (_c *MonitorRuntimeCreate) SetSuccessCount(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetSuccessCount(v)
	return _c
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableSuccessCount(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetSuccessCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *MonitorRuntimeCreate) SetErrorCount(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableErrorCount(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *MonitorRuntimeCreate) SetRetryCount(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableRetryCount(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetConsecutiveSuccesses sets the "consecutive_successes" field.
func (_c *MonitorRuntimeCreate) SetConsecutiveSuccesses(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetConsecutiveSuccesses(v)
	return _c
}

// SetNillableConsecutiveSuccesses sets the "consecutive_successes" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableConsecutiveSuccesses(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetConsecutiveSuccesses(*v)
	}
	return _c
}

// SetConsecutiveErrors sets the "consecutive_errors" field.
func (_c *MonitorRuntimeCreate) SetConsecutiveErrors(v int64) *MonitorRuntimeCreate {
	_c.mutation.SetConsecutiveErrors(v)
	return _c
}

// SetNillableConsecutiveErrors sets the "consecutive_errors" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableConsecutiveErrors(v *int64) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetConsecutiveErrors(*v)
	}
	return _c
}

// SetLastCheckAt sets the "last_check_at" field.
func (_c *MonitorRuntimeCreate) SetLastCheckAt(v time.Time) *MonitorRuntimeCreate {
	_c.mutation.SetLastCheckAt(v)
	return _c
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastCheckAt(v *time.Time) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastCheckAt(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *MonitorRuntimeCreate) SetLastSuccessAt(v time.Time) *MonitorRuntimeCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastSuccessAt(v *time.Time) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetLastErrorAt sets the "last_error_at" field.
func (_c *MonitorRuntimeCreate) SetLastErrorAt(v time.Time) *MonitorRuntimeCreate {
	_c.mutation.SetLastErrorAt(v)
	return _c
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastErrorAt(v *time.Time) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastErrorAt(*v)
	}
	return _c
}

// SetLastStatusCode sets the "last_status_code" field.
func (_c *MonitorRuntimeCreate) SetLastStatusCode(v int) *MonitorRuntimeCreate {
	_c.mutation.SetLastStatusCode(v)
	return _c
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastStatusCode(v *int) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastStatusCode(*v)
	}
	return _c
}

// SetLastDurationMs sets the "last_duration_ms" field.
func (_c *MonitorRuntimeCreate) SetLastDurationMs(v int) *MonitorRuntimeCreate {
	_c.mutation.SetLastDurationMs(v)
	return _c
}

// SetNillableLastDurationMs sets the "last_duration_ms" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastDurationMs(v *int) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastDurationMs(*v)
	}
	return _c
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_c *MonitorRuntimeCreate) SetLastErrorMessage(v string) *MonitorRuntimeCreate {
	_c.mutation.SetLastErrorMessage(v)
	return _c
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableLastErrorMessage(v *string) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetLastErrorMessage(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *MonitorRuntimeCreate) SetNextRunAt(v time.Time) *MonitorRuntimeCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableNextRunAt(v *time.Time) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MonitorRuntimeCreate) SetUpdatedAt(v time.Time) *MonitorRuntimeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MonitorRuntimeCreate) SetNillableUpdatedAt(v *time.Time) *MonitorRuntimeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMonitorID sets the "monitor" edge to the Monitor entity by ID.
func (_c *MonitorRuntimeCreate) SetMonitorID(id int) *MonitorRuntimeCreate {
	_c.mutation.SetMonitorID(id)
	return _c
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (_c *MonitorRuntimeCreate) SetMonitor(v *Monitor) *MonitorRuntimeCreate {
	return _c.SetMonitorID(v.ID)
}

// Mutation returns the MonitorRuntimeMutation object of the builder.
func (_c *MonitorRuntimeCreate) Mutation() *MonitorRuntimeMutation {
	return _c.mutation
}

// Save creates the MonitorRuntime in the database.
func (_c *MonitorRuntimeCreate) Save(ctx context.Context) (*MonitorRuntime, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MonitorRuntimeCreate) SaveX(ctx context.Context) *MonitorRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorRuntimeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorRuntimeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MonitorRuntimeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := monitorruntime.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CheckCount(); !ok {
		v := monitorruntime.DefaultCheckCount
		_c.mutation.SetCheckCount(v)
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		v := monitorruntime.DefaultSuccessCount
		_c.mutation.SetSuccessCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := monitorruntime.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := monitorruntime.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.ConsecutiveSuccesses(); !ok {
		v := monitorruntime.DefaultConsecutiveSuccesses
		_c.mutation.SetConsecutiveSuccesses(v)
	}
	if _, ok := _c.mutation.ConsecutiveErrors(); !ok {
		v := monitorruntime.DefaultConsecutiveErrors
		_c.mutation.SetConsecutiveErrors(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := monitorruntime.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MonitorRuntimeCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MonitorRuntime.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := monitorruntime.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MonitorRuntime.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckCount(); !ok {
		return &ValidationError{Name: "check_count", err: errors.New(`ent: missing required field "MonitorRuntime.check_count"`)}
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		return &ValidationError{Name: "success_count", err: errors.New(`ent: missing required field "MonitorRuntime.success_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "MonitorRuntime.error_count"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "MonitorRuntime.retry_count"`)}
	}
	if _, ok := _c.mutation.ConsecutiveSuccesses(); !ok {
		return &ValidationError{Name: "consecutive_successes", err: errors.New(`ent: missing required field "MonitorRuntime.consecutive_successes"`)}
	}
	if _, ok := _c.mutation.ConsecutiveErrors(); !ok {
		return &ValidationError{Name: "consecutive_errors", err: errors.New(`ent: missing required field "MonitorRuntime.consecutive_errors"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MonitorRuntime.updated_at"`)}
	}
	if len(_c.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "MonitorRuntime.monitor"`)}
	}
	return nil
}

func (_c *MonitorRuntimeCreate) sqlSave(ctx context.Context) (*MonitorRuntime, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MonitorRuntimeCreate) createSpec() (*MonitorRuntime, *sqlgraph.CreateSpec) {
	var (
		_node = &MonitorRuntime{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(monitorruntime.Table, sqlgraph.NewFieldSpec(monitorruntime.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(monitorruntime.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CheckCount(); ok {
		_spec.SetField(monitorruntime.FieldCheckCount, field.TypeInt64, value)
		_node.CheckCount = value
	}
	if value, ok := _c.mutation.SuccessCount(); ok {
		_spec.SetField(monitorruntime.FieldSuccessCount, field.TypeInt64, value)
		_node.SuccessCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(monitorruntime.FieldErrorCount, field.TypeInt64, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(monitorruntime.FieldRetryCount, field.TypeInt64, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.ConsecutiveSuccesses(); ok {
		_spec.SetField(monitorruntime.FieldConsecutiveSuccesses, field.TypeInt64, value)
		_node.ConsecutiveSuccesses = value
	}
	if value, ok := _c.mutation.ConsecutiveErrors(); ok {
		_spec.SetField(monitorruntime.FieldConsecutiveErrors, field.TypeInt64, value)
		_node.ConsecutiveErrors = value
	}
	if value, ok := _c.mutation.LastCheckAt(); ok {
		_spec.SetField(monitorruntime.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(monitorruntime.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if value, ok := _c.mutation.LastErrorAt(); ok {
		_spec.SetField(monitorruntime.FieldLastErrorAt, field.TypeTime, value)
		_node.LastErrorAt = &value
	}
	if value, ok := _c.mutation.LastStatusCode(); ok {
		_spec.SetField(monitorruntime.FieldLastStatusCode, field.TypeInt, value)
		_node.LastStatusCode = &value
	}
	if value, ok := _c.mutation.LastDurationMs(); ok {
		_spec.SetField(monitorruntime.FieldLastDurationMs, field.TypeInt, value)
		_node.LastDurationMs = &value
	}
	if value, ok := _c.mutation.LastErrorMessage(); ok {
		_spec.SetField(monitorruntime.FieldLastErrorMessage, field.TypeString, value)
		_node.LastErrorMessage = &value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(monitorruntime.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(monitorruntime.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   monitorruntime.MonitorTable,
			Columns: []string{monitorruntime.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.monitor_runtime = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MonitorRuntimeCreateBulk is the builder for creating many MonitorRuntime entities in bulk.
type MonitorRuntimeCreateBulk struct {
	config
	err      error
	builders []*MonitorRuntimeCreate
}

// Save creates the MonitorRuntime entities in the database.
func (_c *MonitorRuntimeCreateBulk) Save(ctx context.Context) ([]*MonitorRuntime, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MonitorRuntime, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorRuntimeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MonitorRuntimeCreateBulk) SaveX(ctx context.Context) []*MonitorRuntime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorRuntimeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorRuntimeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
