// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationchannel"
	"goanna/apps/api/ent/notificationevent"
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationEventUpdate is the builder for updating NotificationEvent entities.
type NotificationEventUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationEventMutation
}

// Where appends a list predicates to the NotificationEventUpdate builder.
func (_u *NotificationEventUpdate) Where(ps ...predicate.NotificationEvent) *NotificationEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationEventUpdate) SetStatus(v string) *NotificationEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationEventUpdate) SetNillableStatus(v *string) *NotificationEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationEventUpdate) SetMessage(v string) *NotificationEventUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationEventUpdate) SetNillableMessage(v *string) *NotificationEventUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *NotificationEventUpdate) ClearMessage() *NotificationEventUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationEventUpdate) SetSentAt(v time.Time) *NotificationEventUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationEventUpdate) SetNillableSentAt(v *time.Time) *NotificationEventUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetEndpointID sets the "endpoint" edge to the Endpoint entity by ID.
func (_u *NotificationEventUpdate) SetEndpointID(id int) *NotificationEventUpdate {
	_u.mutation.SetEndpointID(id)
	return _u
}

// SetEndpoint sets the "endpoint" edge to the Endpoint entity.
func (_u *NotificationEventUpdate) SetEndpoint(v *Endpoint) *NotificationEventUpdate {
	return _u.SetEndpointID(v.ID)
}

// SetChannelID sets the "channel" edge to the NotificationChannel entity by ID.
func (_u *NotificationEventUpdate) SetChannelID(id int) *NotificationEventUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the NotificationChannel entity.
func (_u *NotificationEventUpdate) SetChannel(v *NotificationChannel) *NotificationEventUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the NotificationEventMutation object of the builder.
func (_u *NotificationEventUpdate) Mutation() *NotificationEventMutation {
	return _u.mutation
}

// ClearEndpoint clears the "endpoint" edge to the Endpoint entity.
func (_u *NotificationEventUpdate) ClearEndpoint() *NotificationEventUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// ClearChannel clears the "channel" edge to the NotificationChannel entity.
func (_u *NotificationEventUpdate) ClearChannel() *NotificationEventUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationEventUpdate) check() error {
	if _u.mutation.EndpointCleared() && len(_u.mutation.EndpointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationEvent.endpoint"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationEvent.channel"`)
	}
	return nil
}

func (_u *NotificationEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationevent.Table, notificationevent.Columns, sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notificationevent.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(notificationevent.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationevent.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.EndpointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.EndpointTable,
			Columns: []string{notificationevent.EndpointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EndpointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.EndpointTable,
			Columns: []string{notificationevent.EndpointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.ChannelTable,
			Columns: []string{notificationevent.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.ChannelTable,
			Columns: []string{notificationevent.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationEventUpdateOne is the builder for updating a single NotificationEvent entity.
type NotificationEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationEventMutation
}

// SetStatus sets the "status" field.
func (_u *NotificationEventUpdateOne) SetStatus(v string) *NotificationEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationEventUpdateOne) SetNillableStatus(v *string) *NotificationEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationEventUpdateOne) SetMessage(v string) *NotificationEventUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationEventUpdateOne) SetNillableMessage(v *string) *NotificationEventUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *NotificationEventUpdateOne) ClearMessage() *NotificationEventUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationEventUpdateOne) SetSentAt(v time.Time) *NotificationEventUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationEventUpdateOne) SetNillableSentAt(v *time.Time) *NotificationEventUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetEndpointID sets the "endpoint" edge to the Endpoint entity by ID.
func (_u *NotificationEventUpdateOne) SetEndpointID(id int) *NotificationEventUpdateOne {
	_u.mutation.SetEndpointID(id)
	return _u
}

// SetEndpoint sets the "endpoint" edge to the Endpoint entity.
func (_u *NotificationEventUpdateOne) SetEndpoint(v *Endpoint) *NotificationEventUpdateOne {
	return _u.SetEndpointID(v.ID)
}

// SetChannelID sets the "channel" edge to the NotificationChannel entity by ID.
func (_u *NotificationEventUpdateOne) SetChannelID(id int) *NotificationEventUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the NotificationChannel entity.
func (_u *NotificationEventUpdateOne) SetChannel(v *NotificationChannel) *NotificationEventUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the NotificationEventMutation object of the builder.
func (_u *NotificationEventUpdateOne) Mutation() *NotificationEventMutation {
	return _u.mutation
}

// ClearEndpoint clears the "endpoint" edge to the Endpoint entity.
func (_u *NotificationEventUpdateOne) ClearEndpoint() *NotificationEventUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// ClearChannel clears the "channel" edge to the NotificationChannel entity.
func (_u *NotificationEventUpdateOne) ClearChannel() *NotificationEventUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the NotificationEventUpdate builder.
func (_u *NotificationEventUpdateOne) Where(ps ...predicate.NotificationEvent) *NotificationEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationEventUpdateOne) Select(field string, fields ...string) *NotificationEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationEvent entity.
func (_u *NotificationEventUpdateOne) Save(ctx context.Context) (*NotificationEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationEventUpdateOne) SaveX(ctx context.Context) *NotificationEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationEventUpdateOne) check() error {
	if _u.mutation.EndpointCleared() && len(_u.mutation.EndpointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationEvent.endpoint"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationEvent.channel"`)
	}
	return nil
}

func (_u *NotificationEventUpdateOne) sqlSave(ctx context.Context) (_node *NotificationEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationevent.Table, notificationevent.Columns, sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationevent.FieldID)
		for _, f := range fields {
			if !notificationevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notificationevent.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(notificationevent.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationevent.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.EndpointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.EndpointTable,
			Columns: []string{notificationevent.EndpointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EndpointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.EndpointTable,
			Columns: []string{notificationevent.EndpointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.ChannelTable,
			Columns: []string{notificationevent.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationevent.ChannelTable,
			Columns: []string{notificationevent.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
