// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationchannel"
	"goanna/apps/api/ent/notificationevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NotificationEvent is the model entity for the NotificationEvent schema.
type NotificationEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Message holds the value of the "message" field.
	Message *string `json:"message,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt time.Time `json:"sent_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationEventQuery when eager-loading is set.
	Edges                                    NotificationEventEdges `json:"edges"`
	endpoint_notification_events             *int
	notification_channel_notification_events *int
	selectValues                             sql.SelectValues
}

// NotificationEventEdges holds the relations/edges for other nodes in the graph.
type NotificationEventEdges struct {
	// Endpoint holds the value of the endpoint edge.
	Endpoint *Endpoint `json:"endpoint,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *NotificationChannel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EndpointOrErr returns the Endpoint value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEventEdges) EndpointOrErr() (*Endpoint, error) {
	if e.Endpoint != nil {
		return e.Endpoint, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: endpoint.Label}
	}
	return nil, &NotLoadedError{edge: "endpoint"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEventEdges) ChannelOrErr() (*NotificationChannel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: notificationchannel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationevent.FieldID:
			values[i] = new(sql.NullInt64)
		case notificationevent.FieldStatus, notificationevent.FieldMessage:
			values[i] = new(sql.NullString)
		case notificationevent.FieldSentAt:
			values[i] = new(sql.NullTime)
		case notificationevent.ForeignKeys[0]: // endpoint_notification_events
			values[i] = new(sql.NullInt64)
		case notificationevent.ForeignKeys[1]: // notification_channel_notification_events
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationEvent fields.
func (_m *NotificationEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notificationevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case notificationevent.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case notificationevent.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		case notificationevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field endpoint_notification_events", value)
			} else if value.Valid {
				_m.endpoint_notification_events = new(int)
				*_m.endpoint_notification_events = int(value.Int64)
			}
		case notificationevent.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field notification_channel_notification_events", value)
			} else if value.Valid {
				_m.notification_channel_notification_events = new(int)
				*_m.notification_channel_notification_events = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationEvent.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEndpoint queries the "endpoint" edge of the NotificationEvent entity.
func (_m *NotificationEvent) QueryEndpoint() *EndpointQuery {
	return NewNotificationEventClient(_m.config).QueryEndpoint(_m)
}

// QueryChannel queries the "channel" edge of the NotificationEvent entity.
func (_m *NotificationEvent) QueryChannel() *NotificationChannelQuery {
	return NewNotificationEventClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this NotificationEvent.
// Note that you need to call NotificationEvent.Unwrap() before calling this method if this NotificationEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationEvent) Update() *NotificationEventUpdateOne {
	return NewNotificationEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationEvent) Unwrap() *NotificationEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationEvent) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sent_at=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationEvents is a parsable slice of NotificationEvent.
type NotificationEvents []*NotificationEvent
