// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/notificationchannel"
	"goanna/apps/api/ent/notificationevent"
	"goanna/apps/api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationChannelUpdate is the builder for updating NotificationChannel entities.
type NotificationChannelUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdate) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdate) SetName(v string) *NotificationChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableName(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NotificationChannelUpdate) SetKind(v string) *NotificationChannelUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableKind(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *NotificationChannelUpdate) SetTarget(v string) *NotificationChannelUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableTarget(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelUpdate) SetEnabled(v bool) *NotificationChannelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableEnabled(v *bool) *NotificationChannelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_u *NotificationChannelUpdate) AddNotificationEventIDs(ids ...int) *NotificationChannelUpdate {
	_u.mutation.AddNotificationEventIDs(ids...)
	return _u
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_u *NotificationChannelUpdate) AddNotificationEvents(v ...*NotificationEvent) *NotificationChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationEventIDs(ids...)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdate) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearNotificationEvents clears all "notification_events" edges to the NotificationEvent entity.
func (_u *NotificationChannelUpdate) ClearNotificationEvents() *NotificationChannelUpdate {
	_u.mutation.ClearNotificationEvents()
	return _u
}

// RemoveNotificationEventIDs removes the "notification_events" edge to NotificationEvent entities by IDs.
func (_u *NotificationChannelUpdate) RemoveNotificationEventIDs(ids ...int) *NotificationChannelUpdate {
	_u.mutation.RemoveNotificationEventIDs(ids...)
	return _u
}

// RemoveNotificationEvents removes "notification_events" edges to NotificationEvent entities.
func (_u *NotificationChannelUpdate) RemoveNotificationEvents(v ...*NotificationEvent) *NotificationChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationchannel.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := notificationchannel.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.target": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationchannel.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationchannel.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannel.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationEventsIDs(); len(nodes) > 0 && !_u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationChannelUpdateOne is the builder for updating a single NotificationChannel entity.
type NotificationChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdateOne) SetName(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableName(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NotificationChannelUpdateOne) SetKind(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableKind(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *NotificationChannelUpdateOne) SetTarget(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableTarget(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelUpdateOne) SetEnabled(v bool) *NotificationChannelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableEnabled(v *bool) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddNotificationEventIDs adds the "notification_events" edge to the NotificationEvent entity by IDs.
func (_u *NotificationChannelUpdateOne) AddNotificationEventIDs(ids ...int) *NotificationChannelUpdateOne {
	_u.mutation.AddNotificationEventIDs(ids...)
	return _u
}

// AddNotificationEvents adds the "notification_events" edges to the NotificationEvent entity.
func (_u *NotificationChannelUpdateOne) AddNotificationEvents(v ...*NotificationEvent) *NotificationChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationEventIDs(ids...)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdateOne) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearNotificationEvents clears all "notification_events" edges to the NotificationEvent entity.
func (_u *NotificationChannelUpdateOne) ClearNotificationEvents() *NotificationChannelUpdateOne {
	_u.mutation.ClearNotificationEvents()
	return _u
}

// RemoveNotificationEventIDs removes the "notification_events" edge to NotificationEvent entities by IDs.
func (_u *NotificationChannelUpdateOne) RemoveNotificationEventIDs(ids ...int) *NotificationChannelUpdateOne {
	_u.mutation.RemoveNotificationEventIDs(ids...)
	return _u
}

// RemoveNotificationEvents removes "notification_events" edges to NotificationEvent entities.
func (_u *NotificationChannelUpdateOne) RemoveNotificationEvents(v ...*NotificationEvent) *NotificationChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationEventIDs(ids...)
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdateOne) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationChannelUpdateOne) Select(field string, fields ...string) *NotificationChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationChannel entity.
func (_u *NotificationChannelUpdateOne) Save(ctx context.Context) (*NotificationChannel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) SaveX(ctx context.Context) *NotificationChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationchannel.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := notificationchannel.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.target": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationChannelUpdateOne) sqlSave(ctx context.Context) (_node *NotificationChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannel.FieldID)
		for _, f := range fields {
			if !notificationchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationchannel.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationchannel.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannel.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationEventsIDs(); len(nodes) > 0 && !_u.mutation.NotificationEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannel.NotificationEventsTable,
			Columns: []string{notificationchannel.NotificationEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
