// Code generated by ent, DO NOT EDIT.

package ent

import (
	"goanna/apps/api/ent/checkresult"
	"goanna/apps/api/ent/endpoint"
	"goanna/apps/api/ent/notificationchannel"
	"goanna/apps/api/ent/notificationevent"
	"goanna/apps/api/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	checkresultFields := schema.CheckResult{}.Fields()
	_ = checkresultFields
	// checkresultDescStatus is the schema descriptor for status field.
	checkresultDescStatus := checkresultFields[0].Descriptor()
	// checkresult.DefaultStatus holds the default value on creation for the status field.
	checkresult.DefaultStatus = checkresultDescStatus.Default.(string)
	// checkresultDescCheckedAt is the schema descriptor for checked_at field.
	checkresultDescCheckedAt := checkresultFields[4].Descriptor()
	// checkresult.DefaultCheckedAt holds the default value on creation for the checked_at field.
	checkresult.DefaultCheckedAt = checkresultDescCheckedAt.Default.(func() time.Time)
	endpointFields := schema.Endpoint{}.Fields()
	_ = endpointFields
	// endpointDescName is the schema descriptor for name field.
	endpointDescName := endpointFields[0].Descriptor()
	// endpoint.NameValidator is a validator for the "name" field. It is called by the builders before save.
	endpoint.NameValidator = endpointDescName.Validators[0].(func(string) error)
	// endpointDescURL is the schema descriptor for url field.
	endpointDescURL := endpointFields[1].Descriptor()
	// endpoint.URLValidator is a validator for the "url" field. It is called by the builders before save.
	endpoint.URLValidator = endpointDescURL.Validators[0].(func(string) error)
	// endpointDescMethod is the schema descriptor for method field.
	endpointDescMethod := endpointFields[2].Descriptor()
	// endpoint.DefaultMethod holds the default value on creation for the method field.
	endpoint.DefaultMethod = endpointDescMethod.Default.(string)
	// endpointDescIntervalSeconds is the schema descriptor for interval_seconds field.
	endpointDescIntervalSeconds := endpointFields[3].Descriptor()
	// endpoint.DefaultIntervalSeconds holds the default value on creation for the interval_seconds field.
	endpoint.DefaultIntervalSeconds = endpointDescIntervalSeconds.Default.(int)
	// endpoint.IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	endpoint.IntervalSecondsValidator = endpointDescIntervalSeconds.Validators[0].(func(int) error)
	// endpointDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	endpointDescTimeoutSeconds := endpointFields[4].Descriptor()
	// endpoint.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	endpoint.DefaultTimeoutSeconds = endpointDescTimeoutSeconds.Default.(int)
	// endpoint.TimeoutSecondsValidator is a validator for the "timeout_seconds" field. It is called by the builders before save.
	endpoint.TimeoutSecondsValidator = endpointDescTimeoutSeconds.Validators[0].(func(int) error)
	// endpointDescExpectedStatus is the schema descriptor for expected_status field.
	endpointDescExpectedStatus := endpointFields[5].Descriptor()
	// endpoint.DefaultExpectedStatus holds the default value on creation for the expected_status field.
	endpoint.DefaultExpectedStatus = endpointDescExpectedStatus.Default.(int)
	// endpoint.ExpectedStatusValidator is a validator for the "expected_status" field. It is called by the builders before save.
	endpoint.ExpectedStatusValidator = endpointDescExpectedStatus.Validators[0].(func(int) error)
	// endpointDescCreatedAt is the schema descriptor for created_at field.
	endpointDescCreatedAt := endpointFields[6].Descriptor()
	// endpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	endpoint.DefaultCreatedAt = endpointDescCreatedAt.Default.(func() time.Time)
	// endpointDescUpdatedAt is the schema descriptor for updated_at field.
	endpointDescUpdatedAt := endpointFields[7].Descriptor()
	// endpoint.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	endpoint.DefaultUpdatedAt = endpointDescUpdatedAt.Default.(func() time.Time)
	// endpoint.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	endpoint.UpdateDefaultUpdatedAt = endpointDescUpdatedAt.UpdateDefault.(func() time.Time)
	notificationchannelFields := schema.NotificationChannel{}.Fields()
	_ = notificationchannelFields
	// notificationchannelDescName is the schema descriptor for name field.
	notificationchannelDescName := notificationchannelFields[0].Descriptor()
	// notificationchannel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	notificationchannel.NameValidator = notificationchannelDescName.Validators[0].(func(string) error)
	// notificationchannelDescKind is the schema descriptor for kind field.
	notificationchannelDescKind := notificationchannelFields[1].Descriptor()
	// notificationchannel.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	notificationchannel.KindValidator = notificationchannelDescKind.Validators[0].(func(string) error)
	// notificationchannelDescTarget is the schema descriptor for target field.
	notificationchannelDescTarget := notificationchannelFields[2].Descriptor()
	// notificationchannel.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	notificationchannel.TargetValidator = notificationchannelDescTarget.Validators[0].(func(string) error)
	// notificationchannelDescEnabled is the schema descriptor for enabled field.
	notificationchannelDescEnabled := notificationchannelFields[3].Descriptor()
	// notificationchannel.DefaultEnabled holds the default value on creation for the enabled field.
	notificationchannel.DefaultEnabled = notificationchannelDescEnabled.Default.(bool)
	// notificationchannelDescCreatedAt is the schema descriptor for created_at field.
	notificationchannelDescCreatedAt := notificationchannelFields[4].Descriptor()
	// notificationchannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationchannel.DefaultCreatedAt = notificationchannelDescCreatedAt.Default.(func() time.Time)
	notificationeventFields := schema.NotificationEvent{}.Fields()
	_ = notificationeventFields
	// notificationeventDescStatus is the schema descriptor for status field.
	notificationeventDescStatus := notificationeventFields[0].Descriptor()
	// notificationevent.DefaultStatus holds the default value on creation for the status field.
	notificationevent.DefaultStatus = notificationeventDescStatus.Default.(string)
	// notificationeventDescSentAt is the schema descriptor for sent_at field.
	notificationeventDescSentAt := notificationeventFields[2].Descriptor()
	// notificationevent.DefaultSentAt holds the default value on creation for the sent_at field.
	notificationevent.DefaultSentAt = notificationeventDescSentAt.Default.(func() time.Time)
}
