// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goanna/apps/api/ent/predicate"
	"goanna/apps/api/ent/systemconfig"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemConfigUpdate is the builder for updating SystemConfig entities.
type SystemConfigUpdate struct {
	config
	hooks    []Hook
	mutation *SystemConfigMutation
}

// Where appends a list predicates to the SystemConfigUpdate builder.
func (_u *SystemConfigUpdate) Where(ps ...predicate.SystemConfig) *SystemConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *SystemConfigUpdate) SetKey(v string) *SystemConfigUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableKey(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetChecksHistoryLimit sets the "checks_history_limit" field.
func (_u *SystemConfigUpdate) SetChecksHistoryLimit(v int) *SystemConfigUpdate {
	_u.mutation.ResetChecksHistoryLimit()
	_u.mutation.SetChecksHistoryLimit(v)
	return _u
}

// SetNillableChecksHistoryLimit sets the "checks_history_limit" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableChecksHistoryLimit(v *int) *SystemConfigUpdate {
	if v != nil {
		_u.SetChecksHistoryLimit(*v)
	}
	return _u
}

// AddChecksHistoryLimit adds value to the "checks_history_limit" field.
func (_u *SystemConfigUpdate) AddChecksHistoryLimit(v int) *SystemConfigUpdate {
	_u.mutation.AddChecksHistoryLimit(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SystemConfigUpdate) SetTimezone(v string) *SystemConfigUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SystemConfigUpdate) SetNillableTimezone(v *string) *SystemConfigUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *SystemConfigUpdate) ClearTimezone() *SystemConfigUpdate {
	_u.mutation.ClearTimezone()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigUpdate) SetUpdatedAt(v time.Time) *SystemConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemConfigMutation object of the builder.
func (_u *SystemConfigUpdate) Mutation() *SystemConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigUpdate) check() error {
	if v, ok := _u.mutation.ChecksHistoryLimit(); ok {
		if err := systemconfig.ChecksHistoryLimitValidator(v); err != nil {
			return &ValidationError{Name: "checks_history_limit", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.checks_history_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfig.Table, systemconfig.Columns, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChecksHistoryLimit(); ok {
		_spec.SetField(systemconfig.FieldChecksHistoryLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksHistoryLimit(); ok {
		_spec.AddField(systemconfig.FieldChecksHistoryLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(systemconfig.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(systemconfig.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemConfigUpdateOne is the builder for updating a single SystemConfig entity.
type SystemConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemConfigMutation
}

// SetKey sets the "key" field.
func (_u *SystemConfigUpdateOne) SetKey(v string) *SystemConfigUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableKey(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetChecksHistoryLimit sets the "checks_history_limit" field.
func (_u *SystemConfigUpdateOne) SetChecksHistoryLimit(v int) *SystemConfigUpdateOne {
	_u.mutation.ResetChecksHistoryLimit()
	_u.mutation.SetChecksHistoryLimit(v)
	return _u
}

// SetNillableChecksHistoryLimit sets the "checks_history_limit" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableChecksHistoryLimit(v *int) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetChecksHistoryLimit(*v)
	}
	return _u
}

// AddChecksHistoryLimit adds value to the "checks_history_limit" field.
func (_u *SystemConfigUpdateOne) AddChecksHistoryLimit(v int) *SystemConfigUpdateOne {
	_u.mutation.AddChecksHistoryLimit(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SystemConfigUpdateOne) SetTimezone(v string) *SystemConfigUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SystemConfigUpdateOne) SetNillableTimezone(v *string) *SystemConfigUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *SystemConfigUpdateOne) ClearTimezone() *SystemConfigUpdateOne {
	_u.mutation.ClearTimezone()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigUpdateOne) SetUpdatedAt(v time.Time) *SystemConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemConfigMutation object of the builder.
func (_u *SystemConfigUpdateOne) Mutation() *SystemConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemConfigUpdate builder.
func (_u *SystemConfigUpdateOne) Where(ps ...predicate.SystemConfig) *SystemConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemConfigUpdateOne) Select(field string, fields ...string) *SystemConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemConfig entity.
func (_u *SystemConfigUpdateOne) Save(ctx context.Context) (*SystemConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigUpdateOne) SaveX(ctx context.Context) *SystemConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ChecksHistoryLimit(); ok {
		if err := systemconfig.ChecksHistoryLimitValidator(v); err != nil {
			return &ValidationError{Name: "checks_history_limit", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.checks_history_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigUpdateOne) sqlSave(ctx context.Context) (_node *SystemConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfig.Table, systemconfig.Columns, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemconfig.FieldID)
		for _, f := range fields {
			if !systemconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemconfig.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChecksHistoryLimit(); ok {
		_spec.SetField(systemconfig.FieldChecksHistoryLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksHistoryLimit(); ok {
		_spec.AddField(systemconfig.FieldChecksHistoryLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(systemconfig.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(systemconfig.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SystemConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
