// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CheckResult is the predicate function for checkresult builders.
type CheckResult func(*sql.Selector)

// Endpoint is the predicate function for endpoint builders.
type Endpoint func(*sql.Selector)

// NotificationChannel is the predicate function for notificationchannel builders.
type NotificationChannel func(*sql.Selector)

// NotificationEvent is the predicate function for notificationevent builders.
type NotificationEvent func(*sql.Selector)
