// Code generated by ent, DO NOT EDIT.

package notificationchannel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the notificationchannel type in the database.
	Label = "notification_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldBotToken holds the string denoting the bot_token field in the database.
	FieldBotToken = "bot_token"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNotificationEvents holds the string denoting the notification_events edge name in mutations.
	EdgeNotificationEvents = "notification_events"
	// Table holds the table name of the notificationchannel in the database.
	Table = "notification_channels"
	// NotificationEventsTable is the table that holds the notification_events relation/edge.
	NotificationEventsTable = "notification_events"
	// NotificationEventsInverseTable is the table name for the NotificationEvent entity.
	// It exists in this package in order to avoid circular dependency with the "notificationevent" package.
	NotificationEventsInverseTable = "notification_events"
	// NotificationEventsColumn is the table column denoting the notification_events relation/edge.
	NotificationEventsColumn = "notification_channel_notification_events"
)

// Columns holds all SQL columns for notificationchannel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldKind,
	FieldBotToken,
	FieldChatID,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// BotTokenValidator is a validator for the "bot_token" field. It is called by the builders before save.
	BotTokenValidator func(string) error
	// ChatIDValidator is a validator for the "chat_id" field. It is called by the builders before save.
	ChatIDValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindTelegram is the default value of the Kind enum.
const DefaultKind = KindTelegram

// Kind values.
const (
	KindTelegram Kind = "telegram"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindTelegram:
		return nil
	default:
		return fmt.Errorf("notificationchannel: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the NotificationChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByBotToken orders the results by the bot_token field.
func ByBotToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotToken, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNotificationEventsCount orders the results by notification_events count.
func ByNotificationEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationEventsStep(), opts...)
	}
}

// ByNotificationEvents orders the results by notification_events terms.
func ByNotificationEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNotificationEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationEventsTable, NotificationEventsColumn),
	)
}
