// Code generated by ent, DO NOT EDIT.

package checkresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the checkresult type in the database.
	Label = "check_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldResponseTimeMs holds the string denoting the response_time_ms field in the database.
	FieldResponseTimeMs = "response_time_ms"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// EdgeEndpoint holds the string denoting the endpoint edge name in mutations.
	EdgeEndpoint = "endpoint"
	// Table holds the table name of the checkresult in the database.
	Table = "check_results"
	// EndpointTable is the table that holds the endpoint relation/edge.
	EndpointTable = "check_results"
	// EndpointInverseTable is the table name for the Endpoint entity.
	// It exists in this package in order to avoid circular dependency with the "endpoint" package.
	EndpointInverseTable = "endpoints"
	// EndpointColumn is the table column denoting the endpoint relation/edge.
	EndpointColumn = "endpoint_check_results"
)

// Columns holds all SQL columns for checkresult fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldStatusCode,
	FieldResponseTimeMs,
	FieldErrorMessage,
	FieldCheckedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "check_results"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"endpoint_check_results",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCheckedAt holds the default value on creation for the "checked_at" field.
	DefaultCheckedAt func() time.Time
)

// OrderOption defines the ordering options for the CheckResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByResponseTimeMs orders the results by the response_time_ms field.
func ByResponseTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTimeMs, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}

// ByEndpointField orders the results by endpoint field.
func ByEndpointField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEndpointStep(), sql.OrderByField(field, opts...))
	}
}
func newEndpointStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EndpointInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EndpointTable, EndpointColumn),
	)
}
