// Code generated by ent, DO NOT EDIT.

package monitorruntime

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the monitorruntime type in the database.
	Label = "monitor_runtime"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCheckCount holds the string denoting the check_count field in the database.
	FieldCheckCount = "check_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldConsecutiveSuccesses holds the string denoting the consecutive_successes field in the database.
	FieldConsecutiveSuccesses = "consecutive_successes"
	// FieldConsecutiveErrors holds the string denoting the consecutive_errors field in the database.
	FieldConsecutiveErrors = "consecutive_errors"
	// FieldLastCheckAt holds the string denoting the last_check_at field in the database.
	FieldLastCheckAt = "last_check_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastErrorAt holds the string denoting the last_error_at field in the database.
	FieldLastErrorAt = "last_error_at"
	// FieldLastStatusCode holds the string denoting the last_status_code field in the database.
	FieldLastStatusCode = "last_status_code"
	// FieldLastDurationMs holds the string denoting the last_duration_ms field in the database.
	FieldLastDurationMs = "last_duration_ms"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldNextRunAt holds the string denoting the next_run_at field in the database.
	FieldNextRunAt = "next_run_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// Table holds the table name of the monitorruntime in the database.
	Table = "monitor_runtimes"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "monitor_runtimes"
	// MonitorInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorInverseTable = "monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_runtime"
)

// Columns holds all SQL columns for monitorruntime fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCheckCount,
	FieldSuccessCount,
	FieldErrorCount,
	FieldRetryCount,
	FieldConsecutiveSuccesses,
	FieldConsecutiveErrors,
	FieldLastCheckAt,
	FieldLastSuccessAt,
	FieldLastErrorAt,
	FieldLastStatusCode,
	FieldLastDurationMs,
	FieldLastErrorMessage,
	FieldNextRunAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "monitor_runtimes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"monitor_runtime",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCheckCount holds the default value on creation for the "check_count" field.
	DefaultCheckCount int64
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int64
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int64
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int64
	// DefaultConsecutiveSuccesses holds the default value on creation for the "consecutive_successes" field.
	DefaultConsecutiveSuccesses int64
	// DefaultConsecutiveErrors holds the default value on creation for the "consecutive_errors" field.
	DefaultConsecutiveErrors int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusOk       Status = "ok"
	StatusError    Status = "error"
	StatusRetrying Status = "retrying"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusOk, StatusError, StatusRetrying, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("monitorruntime: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MonitorRuntime queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCheckCount orders the results by the check_count field.
func ByCheckCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByConsecutiveSuccesses orders the results by the consecutive_successes field.
func ByConsecutiveSuccesses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveSuccesses, opts...).ToFunc()
}

// ByConsecutiveErrors orders the results by the consecutive_errors field.
func ByConsecutiveErrors(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveErrors, opts...).ToFunc()
}

// ByLastCheckAt orders the results by the last_check_at field.
func ByLastCheckAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastErrorAt orders the results by the last_error_at field.
func ByLastErrorAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorAt, opts...).ToFunc()
}

// ByLastStatusCode orders the results by the last_status_code field.
func ByLastStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatusCode, opts...).ToFunc()
}

// ByLastDurationMs orders the results by the last_duration_ms field.
func ByLastDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDurationMs, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByNextRunAt orders the results by the next_run_at field.
func ByNextRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRunAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, MonitorTable, MonitorColumn),
	)
}
