// Code generated by ent, DO NOT EDIT.

package monitorruntime

import (
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldID, id))
}

// CheckCount applies equality check predicate on the "check_count" field. It's identical to CheckCountEQ.
func CheckCount(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldCheckCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldSuccessCount, v))
}

// ErrorCount applies equality check predicate on the "error_count" field. It's identical to ErrorCountEQ.
func ErrorCount(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldErrorCount, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldRetryCount, v))
}

// ConsecutiveSuccesses applies equality check predicate on the "consecutive_successes" field. It's identical to ConsecutiveSuccessesEQ.
func ConsecutiveSuccesses(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldConsecutiveSuccesses, v))
}

// ConsecutiveErrors applies equality check predicate on the "consecutive_errors" field. It's identical to ConsecutiveErrorsEQ.
func ConsecutiveErrors(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldConsecutiveErrors, v))
}

// LastCheckAt applies equality check predicate on the "last_check_at" field. It's identical to LastCheckAtEQ.
func LastCheckAt(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastCheckAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastErrorAt applies equality check predicate on the "last_error_at" field. It's identical to LastErrorAtEQ.
func LastErrorAt(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastStatusCode applies equality check predicate on the "last_status_code" field. It's identical to LastStatusCodeEQ.
func LastStatusCode(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastStatusCode, v))
}

// LastDurationMs applies equality check predicate on the "last_duration_ms" field. It's identical to LastDurationMsEQ.
func LastDurationMs(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastDurationMs, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastErrorMessage, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldNextRunAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldStatus, vs...))
}

// CheckCountEQ applies the EQ predicate on the "check_count" field.
func CheckCountEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldCheckCount, v))
}

// CheckCountNEQ applies the NEQ predicate on the "check_count" field.
func CheckCountNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldCheckCount, v))
}

// CheckCountIn applies the In predicate on the "check_count" field.
func CheckCountIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldCheckCount, vs...))
}

// CheckCountNotIn applies the NotIn predicate on the "check_count" field.
func CheckCountNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldCheckCount, vs...))
}

// CheckCountGT applies the GT predicate on the "check_count" field.
func CheckCountGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldCheckCount, v))
}

// CheckCountGTE applies the GTE predicate on the "check_count" field.
func CheckCountGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldCheckCount, v))
}

// CheckCountLT applies the LT predicate on the "check_count" field.
func CheckCountLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldCheckCount, v))
}

// CheckCountLTE applies the LTE predicate on the "check_count" field.
func CheckCountLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldCheckCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldSuccessCount, v))
}

// ErrorCountEQ applies the EQ predicate on the "error_count" field.
func ErrorCountEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldErrorCount, v))
}

// ErrorCountNEQ applies the NEQ predicate on the "error_count" field.
func ErrorCountNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldErrorCount, v))
}

// ErrorCountIn applies the In predicate on the "error_count" field.
func ErrorCountIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldErrorCount, vs...))
}

// ErrorCountNotIn applies the NotIn predicate on the "error_count" field.
func ErrorCountNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldErrorCount, vs...))
}

// ErrorCountGT applies the GT predicate on the "error_count" field.
func ErrorCountGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldErrorCount, v))
}

// ErrorCountGTE applies the GTE predicate on the "error_count" field.
func ErrorCountGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldErrorCount, v))
}

// ErrorCountLT applies the LT predicate on the "error_count" field.
func ErrorCountLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldErrorCount, v))
}

// ErrorCountLTE applies the LTE predicate on the "error_count" field.
func ErrorCountLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldErrorCount, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldRetryCount, v))
}

// ConsecutiveSuccessesEQ applies the EQ predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesNEQ applies the NEQ predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesIn applies the In predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldConsecutiveSuccesses, vs...))
}

// ConsecutiveSuccessesNotIn applies the NotIn predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldConsecutiveSuccesses, vs...))
}

// ConsecutiveSuccessesGT applies the GT predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesGTE applies the GTE predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesLT applies the LT predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldConsecutiveSuccesses, v))
}

// ConsecutiveSuccessesLTE applies the LTE predicate on the "consecutive_successes" field.
func ConsecutiveSuccessesLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldConsecutiveSuccesses, v))
}

// ConsecutiveErrorsEQ applies the EQ predicate on the "consecutive_errors" field.
func ConsecutiveErrorsEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldConsecutiveErrors, v))
}

// ConsecutiveErrorsNEQ applies the NEQ predicate on the "consecutive_errors" field.
func ConsecutiveErrorsNEQ(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldConsecutiveErrors, v))
}

// ConsecutiveErrorsIn applies the In predicate on the "consecutive_errors" field.
func ConsecutiveErrorsIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldConsecutiveErrors, vs...))
}

// ConsecutiveErrorsNotIn applies the NotIn predicate on the "consecutive_errors" field.
func ConsecutiveErrorsNotIn(vs ...int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldConsecutiveErrors, vs...))
}

// ConsecutiveErrorsGT applies the GT predicate on the "consecutive_errors" field.
func ConsecutiveErrorsGT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldConsecutiveErrors, v))
}

// ConsecutiveErrorsGTE applies the GTE predicate on the "consecutive_errors" field.
func ConsecutiveErrorsGTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldConsecutiveErrors, v))
}

// ConsecutiveErrorsLT applies the LT predicate on the "consecutive_errors" field.
func ConsecutiveErrorsLT(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldConsecutiveErrors, v))
}

// ConsecutiveErrorsLTE applies the LTE predicate on the "consecutive_errors" field.
func ConsecutiveErrorsLTE(v int64) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldConsecutiveErrors, v))
}

// LastCheckAtEQ applies the EQ predicate on the "last_check_at" field.
func LastCheckAtEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastCheckAt, v))
}

// LastCheckAtNEQ applies the NEQ predicate on the "last_check_at" field.
func LastCheckAtNEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastCheckAt, v))
}

// LastCheckAtIn applies the In predicate on the "last_check_at" field.
func LastCheckAtIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastCheckAt, vs...))
}

// LastCheckAtNotIn applies the NotIn predicate on the "last_check_at" field.
func LastCheckAtNotIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastCheckAt, vs...))
}

// LastCheckAtGT applies the GT predicate on the "last_check_at" field.
func LastCheckAtGT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastCheckAt, v))
}

// LastCheckAtGTE applies the GTE predicate on the "last_check_at" field.
func LastCheckAtGTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastCheckAt, v))
}

// LastCheckAtLT applies the LT predicate on the "last_check_at" field.
func LastCheckAtLT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastCheckAt, v))
}

// LastCheckAtLTE applies the LTE predicate on the "last_check_at" field.
func LastCheckAtLTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastCheckAt, v))
}

// LastCheckAtIsNil applies the IsNil predicate on the "last_check_at" field.
func LastCheckAtIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastCheckAt))
}

// LastCheckAtNotNil applies the NotNil predicate on the "last_check_at" field.
func LastCheckAtNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastCheckAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastErrorAtEQ applies the EQ predicate on the "last_error_at" field.
func LastErrorAtEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastErrorAtNEQ applies the NEQ predicate on the "last_error_at" field.
func LastErrorAtNEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastErrorAt, v))
}

// LastErrorAtIn applies the In predicate on the "last_error_at" field.
func LastErrorAtIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastErrorAt, vs...))
}

// LastErrorAtNotIn applies the NotIn predicate on the "last_error_at" field.
func LastErrorAtNotIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastErrorAt, vs...))
}

// LastErrorAtGT applies the GT predicate on the "last_error_at" field.
func LastErrorAtGT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastErrorAt, v))
}

// LastErrorAtGTE applies the GTE predicate on the "last_error_at" field.
func LastErrorAtGTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastErrorAt, v))
}

// LastErrorAtLT applies the LT predicate on the "last_error_at" field.
func LastErrorAtLT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastErrorAt, v))
}

// LastErrorAtLTE applies the LTE predicate on the "last_error_at" field.
func LastErrorAtLTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastErrorAt, v))
}

// LastErrorAtIsNil applies the IsNil predicate on the "last_error_at" field.
func LastErrorAtIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastErrorAt))
}

// LastErrorAtNotNil applies the NotNil predicate on the "last_error_at" field.
func LastErrorAtNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastErrorAt))
}

// LastStatusCodeEQ applies the EQ predicate on the "last_status_code" field.
func LastStatusCodeEQ(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastStatusCode, v))
}

// LastStatusCodeNEQ applies the NEQ predicate on the "last_status_code" field.
func LastStatusCodeNEQ(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastStatusCode, v))
}

// LastStatusCodeIn applies the In predicate on the "last_status_code" field.
func LastStatusCodeIn(vs ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastStatusCode, vs...))
}

// LastStatusCodeNotIn applies the NotIn predicate on the "last_status_code" field.
func LastStatusCodeNotIn(vs ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastStatusCode, vs...))
}

// LastStatusCodeGT applies the GT predicate on the "last_status_code" field.
func LastStatusCodeGT(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastStatusCode, v))
}

// LastStatusCodeGTE applies the GTE predicate on the "last_status_code" field.
func LastStatusCodeGTE(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastStatusCode, v))
}

// LastStatusCodeLT applies the LT predicate on the "last_status_code" field.
func LastStatusCodeLT(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastStatusCode, v))
}

// LastStatusCodeLTE applies the LTE predicate on the "last_status_code" field.
func LastStatusCodeLTE(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastStatusCode, v))
}

// LastStatusCodeIsNil applies the IsNil predicate on the "last_status_code" field.
func LastStatusCodeIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastStatusCode))
}

// LastStatusCodeNotNil applies the NotNil predicate on the "last_status_code" field.
func LastStatusCodeNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastStatusCode))
}

// LastDurationMsEQ applies the EQ predicate on the "last_duration_ms" field.
func LastDurationMsEQ(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastDurationMs, v))
}

// LastDurationMsNEQ applies the NEQ predicate on the "last_duration_ms" field.
func LastDurationMsNEQ(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastDurationMs, v))
}

// LastDurationMsIn applies the In predicate on the "last_duration_ms" field.
func LastDurationMsIn(vs ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastDurationMs, vs...))
}

// LastDurationMsNotIn applies the NotIn predicate on the "last_duration_ms" field.
func LastDurationMsNotIn(vs ...int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastDurationMs, vs...))
}

// LastDurationMsGT applies the GT predicate on the "last_duration_ms" field.
func LastDurationMsGT(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastDurationMs, v))
}

// LastDurationMsGTE applies the GTE predicate on the "last_duration_ms" field.
func LastDurationMsGTE(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastDurationMs, v))
}

// LastDurationMsLT applies the LT predicate on the "last_duration_ms" field.
func LastDurationMsLT(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastDurationMs, v))
}

// LastDurationMsLTE applies the LTE predicate on the "last_duration_ms" field.
func LastDurationMsLTE(v int) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastDurationMs, v))
}

// LastDurationMsIsNil applies the IsNil predicate on the "last_duration_ms" field.
func LastDurationMsIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastDurationMs))
}

// LastDurationMsNotNil applies the NotNil predicate on the "last_duration_ms" field.
func LastDurationMsNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastDurationMs))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldNextRunAt, v))
}

// NextRunAtIsNil applies the IsNil predicate on the "next_run_at" field.
func NextRunAtIsNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIsNull(FieldNextRunAt))
}

// NextRunAtNotNil applies the NotNil predicate on the "next_run_at" field.
func NextRunAtNotNil() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotNull(FieldNextRunAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMonitor applies the HasEdge predicate on the "monitor" edge.
func HasMonitor() predicate.MonitorRuntime {
	return predicate.MonitorRuntime(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, MonitorTable, MonitorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonitorWith applies the HasEdge predicate on the "monitor" edge with a given conditions (other predicates).
func HasMonitorWith(preds ...predicate.Monitor) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(func(s *sql.Selector) {
		step := newMonitorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonitorRuntime) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonitorRuntime) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonitorRuntime) predicate.MonitorRuntime {
	return predicate.MonitorRuntime(sql.NotPredicates(p))
}
