// Code generated by ent, DO NOT EDIT.

package monitor

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the monitor type in the database.
	Label = "monitor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldAuth holds the string denoting the auth field in the database.
	FieldAuth = "auth"
	// FieldNotificationChannels holds the string denoting the notification_channels field in the database.
	FieldNotificationChannels = "notification_channels"
	// FieldSelector holds the string denoting the selector field in the database.
	FieldSelector = "selector"
	// FieldExpectedType holds the string denoting the expected_type field in the database.
	FieldExpectedType = "expected_type"
	// FieldExpectedResponse holds the string denoting the expected_response field in the database.
	FieldExpectedResponse = "expected_response"
	// FieldCron holds the string denoting the cron field in the database.
	FieldCron = "cron"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCheckResults holds the string denoting the check_results edge name in mutations.
	EdgeCheckResults = "check_results"
	// EdgeNotificationEvents holds the string denoting the notification_events edge name in mutations.
	EdgeNotificationEvents = "notification_events"
	// EdgeRuntime holds the string denoting the runtime edge name in mutations.
	EdgeRuntime = "runtime"
	// Table holds the table name of the monitor in the database.
	Table = "monitors"
	// CheckResultsTable is the table that holds the check_results relation/edge.
	CheckResultsTable = "check_results"
	// CheckResultsInverseTable is the table name for the CheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "checkresult" package.
	CheckResultsInverseTable = "check_results"
	// CheckResultsColumn is the table column denoting the check_results relation/edge.
	CheckResultsColumn = "monitor_check_results"
	// NotificationEventsTable is the table that holds the notification_events relation/edge.
	NotificationEventsTable = "notification_events"
	// NotificationEventsInverseTable is the table name for the NotificationEvent entity.
	// It exists in this package in order to avoid circular dependency with the "notificationevent" package.
	NotificationEventsInverseTable = "notification_events"
	// NotificationEventsColumn is the table column denoting the notification_events relation/edge.
	NotificationEventsColumn = "monitor_notification_events"
	// RuntimeTable is the table that holds the runtime relation/edge.
	RuntimeTable = "monitor_runtimes"
	// RuntimeInverseTable is the table name for the MonitorRuntime entity.
	// It exists in this package in order to avoid circular dependency with the "monitorruntime" package.
	RuntimeInverseTable = "monitor_runtimes"
	// RuntimeColumn is the table column denoting the runtime relation/edge.
	RuntimeColumn = "monitor_runtime"
)

// Columns holds all SQL columns for monitor fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldMethod,
	FieldURL,
	FieldIconURL,
	FieldBody,
	FieldHeaders,
	FieldAuth,
	FieldNotificationChannels,
	FieldSelector,
	FieldExpectedType,
	FieldExpectedResponse,
	FieldCron,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// CronValidator is a validator for the "cron" field. It is called by the builders before save.
	CronValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ExpectedType defines the type for the "expected_type" enum field.
type ExpectedType string

// ExpectedTypeJSON is the default value of the ExpectedType enum.
const DefaultExpectedType = ExpectedTypeJSON

// ExpectedType values.
const (
	ExpectedTypeJSON ExpectedType = "json"
	ExpectedTypeHTML ExpectedType = "html"
	ExpectedTypeText ExpectedType = "text"
)

func (et ExpectedType) String() string {
	return string(et)
}

// ExpectedTypeValidator is a validator for the "expected_type" field enum values. It is called by the builders before save.
func ExpectedTypeValidator(et ExpectedType) error {
	switch et {
	case ExpectedTypeJSON, ExpectedTypeHTML, ExpectedTypeText:
		return nil
	default:
		return fmt.Errorf("monitor: invalid enum value for expected_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the Monitor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// BySelector orders the results by the selector field.
func BySelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelector, opts...).ToFunc()
}

// ByExpectedType orders the results by the expected_type field.
func ByExpectedType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedType, opts...).ToFunc()
}

// ByExpectedResponse orders the results by the expected_response field.
func ByExpectedResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedResponse, opts...).ToFunc()
}

// ByCron orders the results by the cron field.
func ByCron(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCron, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCheckResultsCount orders the results by check_results count.
func ByCheckResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckResultsStep(), opts...)
	}
}

// ByCheckResults orders the results by check_results terms.
func ByCheckResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationEventsCount orders the results by notification_events count.
func ByNotificationEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationEventsStep(), opts...)
	}
}

// ByNotificationEvents orders the results by notification_events terms.
func ByNotificationEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRuntimeField orders the results by runtime field.
func ByRuntimeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuntimeStep(), sql.OrderByField(field, opts...))
	}
}
func newCheckResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckResultsTable, CheckResultsColumn),
	)
}
func newNotificationEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationEventsTable, NotificationEventsColumn),
	)
}
func newRuntimeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuntimeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, RuntimeTable, RuntimeColumn),
	)
}
