// Code generated by ent, DO NOT EDIT.

package monitor

import (
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldID, id))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMethod, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldURL, v))
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldIconURL, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldBody, v))
}

// Selector applies equality check predicate on the "selector" field. It's identical to SelectorEQ.
func Selector(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldSelector, v))
}

// ExpectedResponse applies equality check predicate on the "expected_response" field. It's identical to ExpectedResponseEQ.
func ExpectedResponse(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldExpectedResponse, v))
}

// Cron applies equality check predicate on the "cron" field. It's identical to CronEQ.
func Cron(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCron, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldLabel, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldMethod, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldURL, v))
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldIconURL, v))
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldIconURL, v))
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldIconURL, vs...))
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldIconURL, vs...))
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldIconURL, v))
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldIconURL, v))
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldIconURL, v))
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldIconURL, v))
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldIconURL, v))
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldIconURL, v))
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldIconURL, v))
}

// IconURLIsNil applies the IsNil predicate on the "icon_url" field.
func IconURLIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldIconURL))
}

// IconURLNotNil applies the NotNil predicate on the "icon_url" field.
func IconURLNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldIconURL))
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldIconURL, v))
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldIconURL, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldBody, v))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldBody))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldBody, v))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldHeaders))
}

// AuthIsNil applies the IsNil predicate on the "auth" field.
func AuthIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldAuth))
}

// AuthNotNil applies the NotNil predicate on the "auth" field.
func AuthNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldAuth))
}

// NotificationChannelsIsNil applies the IsNil predicate on the "notification_channels" field.
func NotificationChannelsIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldNotificationChannels))
}

// NotificationChannelsNotNil applies the NotNil predicate on the "notification_channels" field.
func NotificationChannelsNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldNotificationChannels))
}

// SelectorEQ applies the EQ predicate on the "selector" field.
func SelectorEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldSelector, v))
}

// SelectorNEQ applies the NEQ predicate on the "selector" field.
func SelectorNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldSelector, v))
}

// SelectorIn applies the In predicate on the "selector" field.
func SelectorIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldSelector, vs...))
}

// SelectorNotIn applies the NotIn predicate on the "selector" field.
func SelectorNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldSelector, vs...))
}

// SelectorGT applies the GT predicate on the "selector" field.
func SelectorGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldSelector, v))
}

// SelectorGTE applies the GTE predicate on the "selector" field.
func SelectorGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldSelector, v))
}

// SelectorLT applies the LT predicate on the "selector" field.
func SelectorLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldSelector, v))
}

// SelectorLTE applies the LTE predicate on the "selector" field.
func SelectorLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldSelector, v))
}

// SelectorContains applies the Contains predicate on the "selector" field.
func SelectorContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldSelector, v))
}

// SelectorHasPrefix applies the HasPrefix predicate on the "selector" field.
func SelectorHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldSelector, v))
}

// SelectorHasSuffix applies the HasSuffix predicate on the "selector" field.
func SelectorHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldSelector, v))
}

// SelectorIsNil applies the IsNil predicate on the "selector" field.
func SelectorIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldSelector))
}

// SelectorNotNil applies the NotNil predicate on the "selector" field.
func SelectorNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldSelector))
}

// SelectorEqualFold applies the EqualFold predicate on the "selector" field.
func SelectorEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldSelector, v))
}

// SelectorContainsFold applies the ContainsFold predicate on the "selector" field.
func SelectorContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldSelector, v))
}

// ExpectedTypeEQ applies the EQ predicate on the "expected_type" field.
func ExpectedTypeEQ(v ExpectedType) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldExpectedType, v))
}

// ExpectedTypeNEQ applies the NEQ predicate on the "expected_type" field.
func ExpectedTypeNEQ(v ExpectedType) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldExpectedType, v))
}

// ExpectedTypeIn applies the In predicate on the "expected_type" field.
func ExpectedTypeIn(vs ...ExpectedType) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldExpectedType, vs...))
}

// ExpectedTypeNotIn applies the NotIn predicate on the "expected_type" field.
func ExpectedTypeNotIn(vs ...ExpectedType) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldExpectedType, vs...))
}

// ExpectedResponseEQ applies the EQ predicate on the "expected_response" field.
func ExpectedResponseEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldExpectedResponse, v))
}

// ExpectedResponseNEQ applies the NEQ predicate on the "expected_response" field.
func ExpectedResponseNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldExpectedResponse, v))
}

// ExpectedResponseIn applies the In predicate on the "expected_response" field.
func ExpectedResponseIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldExpectedResponse, vs...))
}

// ExpectedResponseNotIn applies the NotIn predicate on the "expected_response" field.
func ExpectedResponseNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldExpectedResponse, vs...))
}

// ExpectedResponseGT applies the GT predicate on the "expected_response" field.
func ExpectedResponseGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldExpectedResponse, v))
}

// ExpectedResponseGTE applies the GTE predicate on the "expected_response" field.
func ExpectedResponseGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldExpectedResponse, v))
}

// ExpectedResponseLT applies the LT predicate on the "expected_response" field.
func ExpectedResponseLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldExpectedResponse, v))
}

// ExpectedResponseLTE applies the LTE predicate on the "expected_response" field.
func ExpectedResponseLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldExpectedResponse, v))
}

// ExpectedResponseContains applies the Contains predicate on the "expected_response" field.
func ExpectedResponseContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldExpectedResponse, v))
}

// ExpectedResponseHasPrefix applies the HasPrefix predicate on the "expected_response" field.
func ExpectedResponseHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldExpectedResponse, v))
}

// ExpectedResponseHasSuffix applies the HasSuffix predicate on the "expected_response" field.
func ExpectedResponseHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldExpectedResponse, v))
}

// ExpectedResponseIsNil applies the IsNil predicate on the "expected_response" field.
func ExpectedResponseIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldExpectedResponse))
}

// ExpectedResponseNotNil applies the NotNil predicate on the "expected_response" field.
func ExpectedResponseNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldExpectedResponse))
}

// ExpectedResponseEqualFold applies the EqualFold predicate on the "expected_response" field.
func ExpectedResponseEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldExpectedResponse, v))
}

// ExpectedResponseContainsFold applies the ContainsFold predicate on the "expected_response" field.
func ExpectedResponseContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldExpectedResponse, v))
}

// CronEQ applies the EQ predicate on the "cron" field.
func CronEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCron, v))
}

// CronNEQ applies the NEQ predicate on the "cron" field.
func CronNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCron, v))
}

// CronIn applies the In predicate on the "cron" field.
func CronIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCron, vs...))
}

// CronNotIn applies the NotIn predicate on the "cron" field.
func CronNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCron, vs...))
}

// CronGT applies the GT predicate on the "cron" field.
func CronGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCron, v))
}

// CronGTE applies the GTE predicate on the "cron" field.
func CronGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCron, v))
}

// CronLT applies the LT predicate on the "cron" field.
func CronLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCron, v))
}

// CronLTE applies the LTE predicate on the "cron" field.
func CronLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCron, v))
}

// CronContains applies the Contains predicate on the "cron" field.
func CronContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldCron, v))
}

// CronHasPrefix applies the HasPrefix predicate on the "cron" field.
func CronHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldCron, v))
}

// CronHasSuffix applies the HasSuffix predicate on the "cron" field.
func CronHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldCron, v))
}

// CronEqualFold applies the EqualFold predicate on the "cron" field.
func CronEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldCron, v))
}

// CronContainsFold applies the ContainsFold predicate on the "cron" field.
func CronContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldCron, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCheckResults applies the HasEdge predicate on the "check_results" edge.
func HasCheckResults() predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CheckResultsTable, CheckResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckResultsWith applies the HasEdge predicate on the "check_results" edge with a given conditions (other predicates).
func HasCheckResultsWith(preds ...predicate.CheckResult) predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := newCheckResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotificationEvents applies the HasEdge predicate on the "notification_events" edge.
func HasNotificationEvents() predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationEventsTable, NotificationEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationEventsWith applies the HasEdge predicate on the "notification_events" edge with a given conditions (other predicates).
func HasNotificationEventsWith(preds ...predicate.NotificationEvent) predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := newNotificationEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRuntime applies the HasEdge predicate on the "runtime" edge.
func HasRuntime() predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, RuntimeTable, RuntimeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuntimeWith applies the HasEdge predicate on the "runtime" edge with a given conditions (other predicates).
func HasRuntimeWith(preds ...predicate.MonitorRuntime) predicate.Monitor {
	return predicate.Monitor(func(s *sql.Selector) {
		step := newRuntimeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.NotPredicates(p))
}
