// Code generated by ent, DO NOT EDIT.

package systemconfig

import (
	"goanna/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldKey, v))
}

// ChecksHistoryLimit applies equality check predicate on the "checks_history_limit" field. It's identical to ChecksHistoryLimitEQ.
func ChecksHistoryLimit(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldChecksHistoryLimit, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldTimezone, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldContainsFold(FieldKey, v))
}

// ChecksHistoryLimitEQ applies the EQ predicate on the "checks_history_limit" field.
func ChecksHistoryLimitEQ(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldChecksHistoryLimit, v))
}

// ChecksHistoryLimitNEQ applies the NEQ predicate on the "checks_history_limit" field.
func ChecksHistoryLimitNEQ(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNEQ(FieldChecksHistoryLimit, v))
}

// ChecksHistoryLimitIn applies the In predicate on the "checks_history_limit" field.
func ChecksHistoryLimitIn(vs ...int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIn(FieldChecksHistoryLimit, vs...))
}

// ChecksHistoryLimitNotIn applies the NotIn predicate on the "checks_history_limit" field.
func ChecksHistoryLimitNotIn(vs ...int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotIn(FieldChecksHistoryLimit, vs...))
}

// ChecksHistoryLimitGT applies the GT predicate on the "checks_history_limit" field.
func ChecksHistoryLimitGT(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGT(FieldChecksHistoryLimit, v))
}

// ChecksHistoryLimitGTE applies the GTE predicate on the "checks_history_limit" field.
func ChecksHistoryLimitGTE(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGTE(FieldChecksHistoryLimit, v))
}

// ChecksHistoryLimitLT applies the LT predicate on the "checks_history_limit" field.
func ChecksHistoryLimitLT(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLT(FieldChecksHistoryLimit, v))
}

// ChecksHistoryLimitLTE applies the LTE predicate on the "checks_history_limit" field.
func ChecksHistoryLimitLTE(v int) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLTE(FieldChecksHistoryLimit, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneIsNil applies the IsNil predicate on the "timezone" field.
func TimezoneIsNil() predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIsNull(FieldTimezone))
}

// TimezoneNotNil applies the NotNil predicate on the "timezone" field.
func TimezoneNotNil() predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotNull(FieldTimezone))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldContainsFold(FieldTimezone, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SystemConfig {
	return predicate.SystemConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemConfig) predicate.SystemConfig {
	return predicate.SystemConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemConfig) predicate.SystemConfig {
	return predicate.SystemConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemConfig) predicate.SystemConfig {
	return predicate.SystemConfig(sql.NotPredicates(p))
}
