// Code generated by ent, DO NOT EDIT.

package endpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the endpoint type in the database.
	Label = "endpoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldIntervalSeconds holds the string denoting the interval_seconds field in the database.
	FieldIntervalSeconds = "interval_seconds"
	// FieldTimeoutSeconds holds the string denoting the timeout_seconds field in the database.
	FieldTimeoutSeconds = "timeout_seconds"
	// FieldExpectedStatus holds the string denoting the expected_status field in the database.
	FieldExpectedStatus = "expected_status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCheckResults holds the string denoting the check_results edge name in mutations.
	EdgeCheckResults = "check_results"
	// EdgeNotificationEvents holds the string denoting the notification_events edge name in mutations.
	EdgeNotificationEvents = "notification_events"
	// Table holds the table name of the endpoint in the database.
	Table = "endpoints"
	// CheckResultsTable is the table that holds the check_results relation/edge.
	CheckResultsTable = "check_results"
	// CheckResultsInverseTable is the table name for the CheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "checkresult" package.
	CheckResultsInverseTable = "check_results"
	// CheckResultsColumn is the table column denoting the check_results relation/edge.
	CheckResultsColumn = "endpoint_check_results"
	// NotificationEventsTable is the table that holds the notification_events relation/edge.
	NotificationEventsTable = "notification_events"
	// NotificationEventsInverseTable is the table name for the NotificationEvent entity.
	// It exists in this package in order to avoid circular dependency with the "notificationevent" package.
	NotificationEventsInverseTable = "notification_events"
	// NotificationEventsColumn is the table column denoting the notification_events relation/edge.
	NotificationEventsColumn = "endpoint_notification_events"
)

// Columns holds all SQL columns for endpoint fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldURL,
	FieldMethod,
	FieldIntervalSeconds,
	FieldTimeoutSeconds,
	FieldExpectedStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// DefaultIntervalSeconds holds the default value on creation for the "interval_seconds" field.
	DefaultIntervalSeconds int
	// IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	IntervalSecondsValidator func(int) error
	// DefaultTimeoutSeconds holds the default value on creation for the "timeout_seconds" field.
	DefaultTimeoutSeconds int
	// TimeoutSecondsValidator is a validator for the "timeout_seconds" field. It is called by the builders before save.
	TimeoutSecondsValidator func(int) error
	// DefaultExpectedStatus holds the default value on creation for the "expected_status" field.
	DefaultExpectedStatus int
	// ExpectedStatusValidator is a validator for the "expected_status" field. It is called by the builders before save.
	ExpectedStatusValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Endpoint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByIntervalSeconds orders the results by the interval_seconds field.
func ByIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalSeconds, opts...).ToFunc()
}

// ByTimeoutSeconds orders the results by the timeout_seconds field.
func ByTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutSeconds, opts...).ToFunc()
}

// ByExpectedStatus orders the results by the expected_status field.
func ByExpectedStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCheckResultsCount orders the results by check_results count.
func ByCheckResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckResultsStep(), opts...)
	}
}

// ByCheckResults orders the results by check_results terms.
func ByCheckResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationEventsCount orders the results by notification_events count.
func ByNotificationEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationEventsStep(), opts...)
	}
}

// ByNotificationEvents orders the results by notification_events terms.
func ByNotificationEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCheckResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckResultsTable, CheckResultsColumn),
	)
}
func newNotificationEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationEventsTable, NotificationEventsColumn),
	)
}
